////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
/////////////////////////////////////             DIVINE SPELLS               //////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Reorganize by level...(though, it's fine to keep the files in the same place...)
//Informal prefix seperating different spelltypes

//xx = consecutive, but otherwise random, numbers
//n = spell level

//zero level cantrips: b_wc_1xx (wizard cantrips)
//zero level cantrips: b_pc_1xx (priest cantrips)

//1st level cantrips: b_1w1xx (wizard cantrips)
//1st level cantrips: b_2c1xx (priest cantrips)

//Regular added spells b_wnxx(wizard spells)
//Regular added spells b_pnxx(priest spells)

/*
opcode = 177
target = 2
power = 0
timing = 4
parameter1 = 5
parameter2 = 160
power = 0
resist_dispel = 2
duration = 1
probability1 = 100
probability2 = 0
dicenumber = 0
dicesize = 0
savingthrow = 0
savebonus = 0
header =
insert_point = 7

//EG
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Snilloc's Snowball Swarm_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~Spells/data/iwd_spells/wizard_2/IDPRO217.pro~   //projectile
//VVC
COPY ~Spells/data/iwd_spells/wizard_2/#SSSWARM.vvc~ ~override~   //animation
//bam
COPY ~Spells/data/iwd_spells/wizard_2/SSSWART.BAM~ ~override~   //animation
COPY ~Spells/data/iwd_spells/wizard_2/SSSWARR.BAM~ ~override~   //animation
COPY ~Spells/data/iwd_spells/wizard_2/SSSWARX.BAM~ ~override~   //animation
//animations
//3d animation
//sounds
COPY ~Spells/data/iwd_spells/wizard_2/TRA_18.WAV~ ~override~   //
COPY ~Spells/data/iwd_spells/wizard_2/RNG_M02.WAV~ ~override~   //
//effs
//Spell itself
ADD_SPELL ~Spells/data/iwd_spells/wizard_2/b_w204.spl~ 2 2 ~WIZARD_SNILLOCS_SNOWBALL_SWARM~ //
        SAY NAME1 @2040000
        SAY NAME2 @2040000
        SAY UNIDENTIFIED_DESC @2040001
	SAY DESC @2040001

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_SNILLOCS_SNOWBALL_SWARM~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//add icons and projectile
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %IDPRO217% STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~Spells/data/iwd_spells/wizard_2/SPWI204a.bam~ ~override/%spell_res%a.bam~
COPY ~Spells/data/iwd_spells/wizard_2/SPWI204b.bam~ ~override/%spell_res%b.bam~
COPY ~Spells/data/iwd_spells/wizard_2/SPWI204c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//Sh. of Entropy immunity list
INCLUDE ~spells/lib/entropy_list.tpa~

FYI   */
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////   Orison   //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////


ACTION_IF FILE_EXISTS_IN_GAME ~b_cant.itm~ BEGIN   //If cantrips are installed  No changes to these spells so far...

END




//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////   Level 1  ///////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Hand of Carnage_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//VVC
//bam
//animations
//3d animation
//sounds
//Spell itself
ADD_SPELL ~spells/spheres/spells/Destruction/b_pr101.spl~ 1 1 ~CLERIC_HAND_OF_CARNAGE~ //
	SAY NAME1 @50401
	SAY NAME2 @50401
	SAY UNIDENTIFIED_DESC @50402
	SAY DESC @50402

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_HAND_OF_CARNAGE~
  RET spell_res
END
//effs
COPY ~spells/spheres/spells/Destruction/b_pr101.eff~ ~override/%spell_res%B.eff~
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 248            //
      STR_VAR resource = EVAL ~%spell_res%B~
  END      //
//add icons and projectile
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~spells/spheres/spells/Destruction/b_c101a.bam~ ~override/%spell_res%a.bam~
COPY ~spells/spheres/spells/Destruction/b_c101b.bam~ ~override/%spell_res%b.bam~
COPY ~spells/spheres/spells/Destruction/b_c101c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//Portrait Icons
//Icon itself
COPY ~spells/spheres/spells/Destruction/B_SMITE.bam~ ~override~
 SET strref = RESOLVE_STR_REF(@50401)

//Thanks kjeron and argent77!!!
//BG(2)EE only for now (i.e. not IWDEE--Need update)
ACTION_IF GAME_IS ~bgee bg2ee eet~ THEN BEGIN
 COPY_EXISTING ~STATDESC.2DA~ override
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  SET max = 0
  FOR (i = 0; i < rows; ++i) BEGIN
   READ_2DA_ENTRY i 0 cols num
   PATCH_IF num > max BEGIN max = num END
  END
SET max += 1
INSERT_2DA_ROW rows cols ~%max%   %strref%   B_SMITE~
PRETTY_PRINT_2DA
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = %max% END           //
END

//IWDEE just use smite display string
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
 COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = 146 END           //
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Frost Fingers_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
ADD_PROJECTILE ~spells/spheres/spells/water/B_C103.pro~   //projectile
//VVC
//bam
COPY ~spells/spheres/spells/water/cocoldt.bam~ ~override~ // Frost Fingers
//animations
//3d animation
//sounds
COPY ~Spells/data/iwd_spells/wizard_2/TRA_18.WAV~ ~override~   //
//effs
//Spell itself
ADD_SPELL ~spells/spheres/spells/water/b_c103.spl~ 1 1 ~CLERIC_FROST_FINGERS~ //
        SAY NAME1 @51707
        SAY NAME2 @51707
        SAY UNIDENTIFIED_DESC @51708
	SAY DESC @51708

//
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_FROST_FINGERS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
//add icons and projectile
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %B_C103% STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~spells/spheres/spells/water/B_C103a.bam~ ~override/%spell_res%a.bam~
COPY ~spells/spheres/spells/water/B_C103b.bam~ ~override/%spell_res%b.bam~
COPY ~spells/spheres/spells/water/B_C103c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Eyes of the Dead____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//MAKE PORTRAIT ICON FOR CASTER (Impeded while active)
//MAKE SO CAN"T CAST OTHER 'EYe' like spells (Wizard eye/Animal eyes)

//Projectile
//VVC
//bam
//animations
//3d animation
//sounds
COPY ~spells/spheres/spells/death/#EFF_E04.wav~ ~override~ // #EFF_P04
COPY ~spells/spheres/spells/death/#EFF_P04.wav~ ~override~ //
//effs
//Spell itself
ADD_SPELL ~spells/spheres/spells/death/b_c104.spl~ 1 1 ~CLERIC_EYES_OF_THE_DEAD~ //
        SAY NAME1 @50304
        SAY NAME2 @50304
        SAY UNIDENTIFIED_DESC @50305
	SAY DESC @50305

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_EYES_OF_THE_DEAD~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//add icons and projectile
  LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~spells/spheres/spells/death/b_c104a.bam~ ~override/%spell_res%a.bam~
COPY ~spells/spheres/spells/death/b_c104b.bam~ ~override/%spell_res%b.bam~
COPY ~spells/spheres/spells/death/b_c104c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//if 0 lev cantrips installed, change to orison
ACTION_IF FILE_EXISTS_IN_GAME ~b_cant.itm~ BEGIN
//change level to Orison
COPY_EXISTING ~%spell_res%.spl~ ~override~
 SPRINT old @11//old text
 SPRINT new @12//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old with new (charm to thought sphere)
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  // Now, actually make it a 0 level spell
COPY_EXISTING ~%spell_res%.spl~ ~override~
 WRITE_BYTE 0x1c 4//Innate
 WRITE_BYTE 0x21 (THIS | 0b11000000)
 LPF ALTER_SPELL_HEADER INT_VAR location = 4 END   //innate location
//global
COPY_EXISTING ~%spell_res%.spl~ ~override~
	PATCH_IF (~%SOURCE_SIZE%~ > ~0x71~) BEGIN
		   READ_SHORT 0x1c spell_type
PATCH_IF  (%spell_type% = 4) BEGIN
        READ_LONG 	0x64	ab_off			// Abilities Offset
	READ_SHORT	0x68	ab_num			// Number of Abilities
	READ_SHORT	0x6a	fx_off			// Effects Offset
	READ_SHORT	0x70	glob_fx			// Number of Global Effects
	SET	glob_add = 0

	INSERT_BYTES (fx_off) 0x30
	  WRITE_SHORT (fx_off) 171			// Give innate
	  WRITE_BYTE (fx_off + 0x2) 1			// Target Self
	  WRITE_BYTE (fx_off + 0x3) 1			// power
	  WRITE_LONG (fx_off + 0x8) 0			// Wizard
	  WRITE_LONG (fx_off + 0xc) 9			// perm
	  WRITE_BYTE (fx_off + 0x12) 100		// Probability 1
	  WRITE_ASCIIE (fx_off + 0x14) ~%spell_res%~	// resource
	++glob_add

        INSERT_BYTES (fx_off) 0x30
	  WRITE_SHORT (fx_off) 172			// Remove spell
	  WRITE_BYTE (fx_off + 0x2) 1			// Target Self
	  WRITE_BYTE (fx_off + 0x3) 1			// power
	  WRITE_LONG (fx_off + 0x8) 0			// Wizard
	  WRITE_LONG (fx_off + 0xc) 9			// perm
	  WRITE_BYTE (fx_off + 0x12) 100		// Probability 1
	  WRITE_ASCIIE (fx_off + 0x14) ~%spell_res%~	// resource
	++glob_add

//	INSERT_BYTES (fx_off) 0x30			//Second effect
//	  WRITE_etc...
//	++glob_add

	glob_fx += glob_add
	WRITE_SHORT 0x70 glob_fx			// Increment Number of Global Effects
	FOR (i = 0; i < ab_num; ++i) BEGIN		// Offset Effect Index for all Abilities
	  READ_SHORT (ab_off + i * 0x28 + 0x20) fx_idx
	  WRITE_SHORT (ab_off + i * 0x28 + 0x20) (fx_idx + glob_add)
	END
END
END

//NOTE: IF CANTRIPS INSTALLED, FNP NEEDS TO CHECK FOR THAT, AND MAKE PROPER ADJUSTMENTS
END  //end Cantrip compatibility

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Disrupt Undead______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//VVC
//bam
//animations
//3d animation
//sounds
COPY ~spells/spheres/spells/death/#EFF_E04.wav~ ~override~ // Added for eyes of dead...still, copying over just in case
COPY ~spells/spheres/spells/death/#EFF_P04.wav~ ~override~ //
//effs
//Spell itself
ADD_SPELL ~spells/spheres/spells/death/b_c105.spl~ 1 1 ~CLERIC_DISRUPT_UNDEAD~ //
        SAY NAME1 @50307
        SAY NAME2 @50307
        SAY UNIDENTIFIED_DESC @50308
	SAY DESC @50308

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_DISRUPT_UNDEAD~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//add icons and projectile
  LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~spells/spheres/spells/death/b_c105a.bam~ ~override/%spell_res%a.bam~
COPY ~spells/spheres/spells/death/b_c105b.bam~ ~override/%spell_res%b.bam~
COPY ~spells/spheres/spells/death/b_c105c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Animal Eyes_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//VVC
//bam
//animations
//3d animation
//sounds
COPY ~spells/spheres/spells/death/#EFF_E04.wav~ ~override~ // Already copied over (at least) twice, but just in case...
COPY ~spells/spheres/spells/death/#EFF_P04.wav~ ~override~ //
//effs
//Spell itself
ADD_SPELL ~spells/spheres/spells/animal/b_c102.spl~ 1 1 ~CLERIC_ANIMAL_EYES~ //
        SAY NAME1 @51101
        SAY NAME2 @51101
        SAY UNIDENTIFIED_DESC @51102
	SAY DESC @51102

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_ANIMAL_EYES~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
//add icons and projectile
  LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~spells/spheres/spells/animal/b_c102a.bam~ ~override/%spell_res%a.bam~
COPY ~spells/spheres/spells/animal/b_c102b.bam~ ~override/%spell_res%b.bam~
COPY ~spells/spheres/spells/animal/b_c102c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~



//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////   Level 2  ///////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Shatter_____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Projectile
//VVC
//bam
//animations
//3d animation
//sounds
COPY ~spells/spheres/spells/Destruction/EFF_E05.wav~ ~override~ //
//effs
//Spell itself
ADD_SPELL ~spells/spheres/spells/Destruction/b_pr201.spl~ 1 2 ~CLERIC_SHATTER~ //
        SAY NAME1 @50408
        SAY NAME2 @50408
        SAY UNIDENTIFIED_DESC @50409
	SAY DESC @50409
//
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_SHATTER~
  RET spell_res
END
//sec spells
COPY ~spells/spheres/spells/Destruction/b_pr201A.spl~ ~override/%spell_res%A.spl~ // Shatter 2nd
  LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource = EVAL  ~B_PR201A~ resource =  EVAL  ~%spell_res%A~ END
  LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource = EVAL  ~B_PR201C~ resource =  EVAL  ~%spell_res%C~ END
  LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource = EVAL  ~B_PR201D~ resource =  EVAL  ~%spell_res%D~ END
COPY ~spells/spheres/spells/Destruction/b_pr201B.spl~ ~override/%spell_res%B.spl~ // Shatter   3rd
  LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource = EVAL  ~B_PR201A~ resource =  EVAL  ~%spell_res%A~ END
  LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource = EVAL  ~B_PR201C~ resource =  EVAL  ~%spell_res%C~ END
COPY ~spells/spheres/spells/Destruction/b_pr201A.eff~ ~override/%spell_res%A.eff~ // Shatter  x dam golem
COPY ~spells/spheres/spells/Destruction/b_pr201B.eff~ ~override/%spell_res%B.eff~ // Shatter  cast 2
  WRITE_EVALUATED_ASCII 0x0030 ~%spell_res%A~
COPY ~spells/spheres/spells/Destruction/b_pr201C.eff~ ~override/%spell_res%C.eff~ // Shatter  x dam
COPY ~spells/spheres/spells/Destruction/b_pr201D.eff~ ~override/%spell_res%D.eff~ // Shatter  cast 3
  WRITE_EVALUATED_ASCII 0x0030 ~%spell_res%B~
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource = ~B_PR201A~ resource =  EVAL  ~%spell_res%A~ END
  LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource = ~B_PR201B~ resource =  EVAL  ~%spell_res%B~ END
  LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource = ~B_PR201C~ resource =  EVAL  ~%spell_res%C~ END
  LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource = ~B_PR201D~ resource =  EVAL  ~%spell_res%D~ END

//add icons and projectile
  LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~spells/spheres/spells/Destruction/B_C204a.bam~ ~override/%spell_res%a.bam~
COPY ~spells/spheres/spells/Destruction/B_C204b.bam~ ~override/%spell_res%b.bam~
COPY ~spells/spheres/spells/Destruction/B_C204c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Ice Blade_________________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



//Projectile
//VVC
//bam
//animations
//3d animation
//sounds
//itms
//blades
COPY ~spells/spheres/spells/water/moonbla.bam~ ~override~   //bam
COPY ~spells/spheres/spells/water/b_iceb1.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51710
	    SAY DESC @51710
COPY ~spells/spheres/spells/water/b_iceb2.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51711
	    SAY DESC @51711
COPY ~spells/spheres/spells/water/b_iceb3.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51712
	    SAY DESC @51712
COPY ~spells/spheres/spells/water/b_iceb4.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51713
	    SAY DESC @51713
COPY ~spells/spheres/spells/water/b_iceb5.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51714
	    SAY DESC @51714
COPY ~spells/spheres/spells/water/b_iceb6.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51715
	SAY DESC @51715
COPY ~spells/spheres/spells/water/b_iceb7.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51716
	SAY DESC @51716
COPY ~spells/spheres/spells/water/b_iceb8.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51717
	SAY DESC @51717
COPY ~spells/spheres/spells/water/b_iceb9.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51718
	SAY DESC @51718
COPY ~spells/spheres/spells/water/b_iceb10.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51719
	SAY DESC @51719
//effs
//Spell itself
ADD_SPELL ~spells/spheres/spells/water/b_c203.spl~ 1 2 ~CLERIC_ICE_BLADE~ //
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51705
        SAY DESC @51705

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_ICE_BLADE~
  RET spell_res
END
//add icons and projectile
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~spells/spheres/spells/water/b_c203a.bam~ ~override/%spell_res%a.bam~
COPY ~spells/spheres/spells/water/b_c203b.bam~ ~override/%spell_res%b.bam~
COPY ~spells/spheres/spells/water/b_c203c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~






//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Pacify the Dead___________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Make custom icon (may be cast at undead npcs)

//Projectile
//VVC
//bam
//animations
//3d animation
//sounds
COPY ~spells/spheres/spells/death/#EFF_E04.wav~ ~override~ // Already copied over (at least) twice, but just in case...
COPY ~spells/spheres/spells/death/#EFF_P04.wav~ ~override~ //
//effs
//Spell itself
ADD_SPELL ~spells/spheres/spells/death/b_c202.spl~ 1 2 ~CLERIC_PACIFY_DEAD~ //
        SAY NAME1 @50301
        SAY NAME2 @50301
        SAY UNIDENTIFIED_DESC @50302
	SAY DESC @50302

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_PACIFY_DEAD~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324
      parameter1 = 0
      parameter2 = 2
      STR_VAR resource = EVAL ~%spell_res%~
     END
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 patameter2 = 0 timing = 0 STR_VAR resource = EVAL ~%spell_res%~ END
//  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 patameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_f201~ END

//???????????????
ACTION_IF FILE_EXISTS_IN_GAME ~spwi312.spl~ BEGIN
 COPY_EXISTING ~spwi312.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 patameter2 = 0 timing = 0 STR_VAR resource = EVAL ~%spell_res%~ END
//  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 patameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_f201~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwish25.spl~ BEGIN
 COPY_EXISTING ~spwish25.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 patameter2 = 0 timing = 0 STR_VAR resource = EVAL ~%spell_res%~ END
//  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 patameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_f201~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~spin146.spl~ BEGIN
 COPY_EXISTING ~spin146.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 patameter2 = 0 timing = 0 STR_VAR resource = EVAL ~%spell_res%~ END
//  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 patameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_f201~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~spin977.spl~ BEGIN
 COPY_EXISTING ~spin977.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 patameter2 = 0 timing = 0 STR_VAR resource = EVAL ~%spell_res%~ END
//  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 patameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_f201~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwm164.spl~ BEGIN
 COPY_EXISTING ~spwm164.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 patameter2 = 0 timing = 0 STR_VAR resource = EVAL ~%spell_res%~ END
//  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 patameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_f201~ END
END
//add icons and projectile
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~spells/spheres/spells/death/b_c202a.bam~ ~override/%spell_res%a.bam~
COPY ~spells/spheres/spells/death/b_c202b.bam~ ~override/%spell_res%b.bam~
COPY ~spells/spheres/spells/death/b_c202c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~




//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Forbiddance_______________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//MAKE CUSTOM ICON

//Projectile
//VVC
//bam
//animations
//3d animation
//sounds
COPY ~spells/spheres/spells/death/#EFF_P04.wav~ ~override~ //
//effs
//Spell itself
ADD_SPELL ~spells/spheres/spells/charm/b_c201.spl~ 1 2 ~CLERIC_FORBID~ //
        SAY NAME1 @50800
        SAY NAME2 @50800
        SAY UNIDENTIFIED_DESC @50801
	SAY DESC @50801

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_FORBID~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324
      STR_VAR resource = EVAL ~%spell_res%~
     END
//add icons and projectile
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~spells/spheres/spells/charm/b_c201a.bam~ ~override/%spell_res%a.bam~
COPY ~spells/spheres/spells/charm/b_c201b.bam~ ~override/%spell_res%b.bam~
COPY ~spells/spheres/spells/charm/b_c201c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~



//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////   Level 3  ///////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Stone Fist________________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


//CONTINUE FROM HERE
/*


// check for SPSTONES.bam
//check for EFF_M08.wav
//Projectile
//VVC
//bam
//animations

//3d animation
//sounds
COPY ~spells/spheres/spells/death/#EFF_P04.wav~ ~override~ //
//effs
//Spell itself
ADD_SPELL ~spells/spheres/spells/earth/b_pr301.spl~ 1 3 ~CLERIC_STONE_FIST~ //
        SAY NAME1 @51501
        SAY NAME2 @51501
        SAY UNIDENTIFIED_DESC @51503
	SAY DESC @51503

//to clear earlier versions of the spell
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_STONE_FIST~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 111
      STR_VAR resource = EVAL ~%spell_res%~
     END
//itm
COPY ~spells/spheres/spells/earth/b_pr301.itm~ ~override/%spell_res%.itm~ // Actual Fist
        SAY NAME1 @51501
        SAY NAME2 @51501
        SAY UNIDENTIFIED_DESC @51504
	SAY DESC @51504

//add icons and projectile
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = EVAL  ~%spell_res%B~ END
COPY ~spells/spheres/spells/earth/b_c303a.bam~ ~override/%spell_res%a.bam~
COPY ~spells/spheres/spells/earth/b_c303b.bam~ ~override/%spell_res%b.bam~
COPY ~spells/spheres/spells/earth/b_c303c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~








//Cloak of Darkness_________________________________________________________
//icons
COPY ~spells/spheres/spells/shadow/b_c302b.bam~ ~override~ // Cloak of Darkness
COPY ~spells/spheres/spells/shadow/b_c302c.bam~ ~override~ // Cloak of Darkness
//spell etc
COPY ~spells/spheres/spells/shadow/b_c302.spl~ ~override~ // Cloak of Darkness
        SAY NAME1 @52003
        SAY NAME2 @52003
        SAY UNIDENTIFIED_DESC @52004
	SAY DESC @52004


//Feral Instinct_____________________________________________________________
//icons
COPY ~spells/spheres/spells/charm/b_c301b.bam~ ~override~ // Murderous Command
COPY ~spells/spheres/spells/charm/b_c301c.bam~ ~override~ // Murderous Command
//spell etc
COPY ~spells/spheres/spells/charm/b_c301.spl~ ~override~ // Murderous Command
        SAY NAME1 @50803
        SAY NAME2 @50803
        SAY UNIDENTIFIED_DESC @50804
	SAY DESC @50804


//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////   Level 4  ///////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Storm Wall________________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


//________________________________________________________________
COPY ~spells/spheres/spells/air/b_elect1.bam~ ~override~ // 
COPY ~spells/spheres/spells/air/b_storm1.vvc~ ~override~ //
COPY ~spells/spheres/spells/air/b_c401a.spl~ ~override~ //sub-spell
ADD_PROJECTILE ~spells/spheres/spells/air/b_storm1.pro~   //pro
COPY ~spells/spheres/spells/air/b_c401.spl~ ~override~ //spell
        SAY NAME1 @51601
        SAY NAME2 @51601
        SAY UNIDENTIFIED_DESC @51602
	SAY DESC @51602
	WRITE_SHORT 0x098 ~%b_storm1%~


//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////   Level 5  ///////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Waves of Agony____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



//__________________________________________________________________________________
COPY ~spells/spheres/spells/affliction/b_Pr501.spl~ ~override~ // Wave of Agony
        SAY NAME1 @51201
        SAY NAME2 @51201
        SAY UNIDENTIFIED_DESC @51202
	SAY DESC @51202
COPY ~spells/spheres/spells/affliction/b_ILM04a.spl~ ~override~ // Wave of Agony spla
COPY ~spells/spheres/spells/affliction/b_ILM04b.spl~ ~override~ // etc.
COPY ~spells/spheres/spells/affliction/b_ILM04.eff~ ~override~ //
  SAY 0x1c @51203 //Wracked in Agony



//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Misfire___________________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//________________________________________________________________
//icons
COPY ~spells/spheres/spells/dread/b_c501b.bam~ ~override~ // Misfire
COPY ~spells/spheres/spells/dread/b_c501c.bam~ ~override~ // Misfire
//spl etc
COPY ~spells/spheres/spells/dread/b_c501.eff~ ~override~ // Misfire
  SAY 0x1c @50901     //Misfire

COPY ~spells/spheres/spells/dread/b_c501.spl~ ~override~ // Misfire
        SAY NAME1 @50901
        SAY NAME2 @50901
        SAY UNIDENTIFIED_DESC @50902
	SAY DESC @50902



//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////   Level 6  ///////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Nature's Wrath____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// 
 COPY ~spells/spheres/spells/plant/b_Pr601.spl~ ~override~
        SAY NAME1 @51401
        SAY NAME2 @51401
        SAY UNIDENTIFIED_DESC @51402
	SAY DESC @51402

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Assassin Vines____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//_________________________________________________
 COPY ~spells/spheres/spells/plant/b_c601.spl~ ~override~ //Assassin Vines
        SAY NAME1 @51404
        SAY NAME2 @51404
        SAY UNIDENTIFIED_DESC @51405
	SAY DESC @51405

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Summon Water Elemental____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//______________________________________________________________________
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN    //IWDEE only animation
 COPY ~spells/spheres/spells/water/b_Pr602.spl~ ~override~ // Summon Water Elemental
        SAY NAME1 @51701
        SAY NAME2 @51701
        SAY UNIDENTIFIED_DESC @51702
	SAY DESC @51702
 COPY ~spells/spheres/spells/water/B_PRWA1.eff~ ~override~ // Summon Water Elemental
 COPY ~spells/spheres/spells/water/B_PRWA2.eff~ ~override~ // Summon Water Elemental
 COPY ~spells/spheres/spells/water/b_wele1.itm~ ~override~ // Summon Water Elemental
 COPY ~spells/spheres/spells/water/b_gensu.itm~ ~override~ // Summon Water Elemental
 COPY_EXISTING ~cywatere.cre~ ~override/b_wele1.cre~
  WRITE_BYTE 0x270 5  //Controlled
  ADD_CRE_ITEM ~b_gensu~ #0 #0 #0 ~IDENTIFIED~ ~amulet~ //Gender to summoned
  ADD_CRE_ITEM ~b_wele1~ #0 #0 #0 ~IDENTIFIED~ ~weapon1~ EQUIP//Adds weapon
  WRITE_ASCII 0x248 ~NONE    ~  //Override script
  WRITE_ASCII 0x250 ~NONE~  //Class script
  WRITE_ASCII 0x258 ~NONE~  //Race script
  WRITE_ASCII 0x260 ~NONE~  //General script
  WRITE_ASCII 0x268 ~BDSUM00~  //Default script
 COPY ~spells/spheres/spells/water/b_wele2.itm~ ~override~ // Summon Water Elemental
 COPY_EXISTING ~cywatere.cre~ ~override/b_wele2.cre~
  WRITE_BYTE 0x270 5  //Controlled
  WRITE_BYTE 0x234 16  //Level
  WRITE_BYTE 0x238 22  //Strength
  WRITE_BYTE 0x23c 15  //Dex
  WRITE_BYTE 0x23d 16  //COn
  WRITE_BYTE 0x52 3  //THAC0
  WRITE_BYTE 0x54 3  //death
  WRITE_BYTE 0x55 5  //Wands
  WRITE_BYTE 0x56 4  //Poly
  WRITE_BYTE 0x57 3  //Breath
  WRITE_BYTE 0x58 6  //Spell
  WRITE_SHORT 0x24 168 //
  WRITE_SHORT 0x26 168 // Current and max hp
  ADD_CRE_ITEM ~b_wele2~ #0 #0 #0 ~IDENTIFIED~ ~weapon1~ EQUIP//Adds weapon
  ADD_CRE_ITEM ~b_gensu~ #0 #0 #0 ~IDENTIFIED~ ~amulet~ //Gender to summoned
  WRITE_ASCII 0x248 ~NONE    ~  //Override script
  WRITE_ASCII 0x250 ~NONE~  //Class script
  WRITE_ASCII 0x258 ~NONE~  //Race script
  WRITE_ASCII 0x260 ~NONE~  //General script
  WRITE_ASCII 0x268 ~BDSUM00~  //Default script
 COPY ~spells/spheres/spells/water/BDSUM00.bcs~ ~override~ // Copys over BDSUM00 script
END
//Add the damn creature to BG1
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN    //BG2EE only creature
 COPY ~spells/spheres/spells/water/b_Pr602.spl~ ~override~ // Summon Water Elemental
        SAY NAME1 @51701
        SAY NAME2 @51701
        SAY UNIDENTIFIED_DESC @51702
	SAY DESC @51702
 COPY ~spells/spheres/spells/water/B_PRWA1.eff~ ~override~ // Summon Water Elemental
 COPY ~spells/spheres/spells/water/B_PRWA2.eff~ ~override~ // Summon Water Elemental
 COPY ~spells/spheres/spells/water/b_wele1.itm~ ~override~ // Summon Water Elemental
 COPY ~spells/spheres/spells/water/b_gensu.itm~ ~override~ // Summon Water Elemental
 COPY_EXISTING ~elwatg01.cre~ ~override/b_wele1.cre~
  WRITE_BYTE 0x270 5  //Controlled
  ADD_CRE_ITEM ~b_gensu~ #0 #0 #0 ~IDENTIFIED~ ~amulet~ //Gender to summoned
  ADD_CRE_ITEM ~b_wele1~ #0 #0 #0 ~IDENTIFIED~ ~weapon1~ EQUIP//Adds weapon
  WRITE_ASCII 0x248 ~NONE~  //Override script
  WRITE_ASCII 0x250 ~NONE~  //Class script
  WRITE_ASCII 0x258 ~NONE~  //Race script
  WRITE_ASCII 0x260 ~NONE~  //General script
  WRITE_ASCII 0x268 ~BDSUM00~  //Default script
 COPY ~spells/spheres/spells/water/b_wele2.itm~ ~override~ // Summon Water Elemental
 COPY_EXISTING ~elwatg01.cre~ ~override/b_wele2.cre~
  WRITE_BYTE 0x270 5  //Controlled
  WRITE_BYTE 0x234 16  //Level
  WRITE_BYTE 0x238 22  //Strength
  WRITE_BYTE 0x23c 15  //Dex
  WRITE_BYTE 0x23d 16  //COn
  WRITE_BYTE 0x52 3  //THAC0
  WRITE_BYTE 0x54 3  //death
  WRITE_BYTE 0x55 5  //Wands
  WRITE_BYTE 0x56 4  //Poly
  WRITE_BYTE 0x57 3  //Breath
  WRITE_BYTE 0x58 6  //Spell
  WRITE_SHORT 0x24 168 //
  WRITE_SHORT 0x26 168 // Current and max hp
  ADD_CRE_ITEM ~b_wele2~ #0 #0 #0 ~IDENTIFIED~ ~weapon1~ EQUIP//Adds weapon
  ADD_CRE_ITEM ~b_gensu~ #0 #0 #0 ~IDENTIFIED~ ~amulet~ //Gender to summoned
  WRITE_ASCII 0x248 ~NONE~  //Override script
  WRITE_ASCII 0x250 ~NONE~  //Class script
  WRITE_ASCII 0x258 ~NONE~  //Race script
  WRITE_ASCII 0x260 ~NONE~  //General script
  WRITE_ASCII 0x268 ~BDSUM00~  //Default script
END

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////   Level 7  ///////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////






*/



