//Priest Orisons b_po###  (010, 020,...990) 010 = @@101000000; 020 = @@102000000...990 = @199000000



////////////////////////////////////////////////////////////////
/////////////////   Cantrips and Orisons    ////////////////////
////////////////////////////////////////////////////////////////

//NOTE: Add compatibility with sphere system
//compatibility: Entropy shield, if present, should protect vs all, or almost all, cantrip projectiles.  

////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////                                  /////////////////////////////
/////////////////////////////               Priest             /////////////////////////////
/////////////////////////////              Orisons             /////////////////////////////
/////////////////////////////                                  /////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Template__________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE: no
//                                          IWDification: no
//                                          My IWD spells: no
//                                          my revised spells: no
//                                          spheres: no
//                                          SR: no
//                                          Other: no





//Ceremony:  A dialog cantrip that allows the priest to do a number of things.  All cost gold
//Ceremony: Bless Water          To add    Implementation: Dialog: costs gold, creates a vial of water that damages undead
//
//Ceremony: Consecrate ground    To add    All enemies in area recieve a -1 penalty to saves.  Cannot be used while enemies present (good for sleeping)
//
//Ceremony: communion            To add    Gives allies a blessing of some sort
//
//Alternatively: Rituals: Cast spells with a gold cost that is more powerful/long lasting than normal (or both?)

//Sense Magic                    To add    just the reveal magic opcode

//                    To Add    Convert 1st level spell to cantrip

//Magic stone                    To add    Convert 1st level spell to cantrip

//Calm                          To add     A single ally saves to remove fear or other issue (possible, I think)try adding (decimal) 0x200 to special to 161 'cure fear'

//Benediction                    To add    Similar to canticle/meditation.  Gives priest bonus to THAC0

//Animal Companion (druid)      To add     animal versions of familliar like spell

//Detect Creature               To add     As track

//Disorient                     To add     Creature hesitates for a moment

//Conjure Critter               To add     Summons a bunny or similar

//Drowse                        To add     3 second unconsciousness

//Fire Bolt                     To add

//Frost Ray                     To add

//Acid splash                   To add

//Magic Bolt                    To add (only with spheres)

//Jolt                          To add  Shocking graps as a cantrip (only with spheres)

//Elemental protection          To add  +5% protect from fire/cold/acid/electricity

//Reprieve                      To add  Decent, but temporary bonus to hit points if below 10% (cast on condition)

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//________________________________________________________________Cure Minor Wounds_________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//cure minor wounds     added               Revised Spells: yes (both ways?)                       Double Checked: no
//                                          (Our) Spheres: NO DO  From 'healing' to 'life'
//                                          Others?

//ADD SPHERE SYSTEM COMPATIBILITY: SPHERE: LIFE  d5_spheres.d5
//STANDARD VERSION
COPY ~spells/data/cantrips/divine/b_po010.spl~ ~override~
        SAY NAME1 @101000000
        SAY NAME2 @101000000
        SAY UNIDENTIFIED_DESC @101000001
	SAY DESC @101000001
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po010.spl~ ~override~
        SAY UNIDENTIFIED_DESC @101000003
	SAY DESC @101000003
END
//Compatibility with Revised Spells
ACTION_IF FILE_EXISTS_IN_GAME ~b_revise.itm~ BEGIN
COPY_EXISTING ~b_po010.spl~ ~override~
        SAY UNIDENTIFIED_DESC @101000002
	SAY DESC @101000002
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 17            //
                  parameter1 = 1
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 17 parameter1 = 10 parameter2 = 2 END
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po010.spl~ ~override~
        SAY UNIDENTIFIED_DESC @101000004
	SAY DESC @101000004
END
END
//spheres

//Change to 10% +1 HP

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//______________________________________________________________________Canticle________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Canticle              Added               Acolyte of Tempus: yes                                 Double Checked: no
//                                          IWDEE: yes         (prayer)  
//                                          IWDIFICATION: yes  (prayer)
//                                          my IWD Spells: Yes (prayer) Both ways
//                                          SR: Needed?

//CHECK SPELL REVISIONS!
COPY ~spells/data/cantrips/divine/b_po020.spl~ ~override~
        SAY NAME1 @102000000
        SAY NAME2 @102000000
        SAY UNIDENTIFIED_DESC @102000001
	SAY DESC @102000001
COPY ~spells/data/cantrips/divine/b_po021.spl~ ~override~      //to remove
        SAY NAME1 @102000002
        SAY NAME2 @102000002
        SAY UNIDENTIFIED_DESC @102000003
	SAY DESC @102000003
COPY ~spells/data/cantrips/divine/b_po022.eff~ ~override~
  SAY 0x1c @102000004 //Chanting
//bless, aid, chant
//bless
COPY_EXISTING ~sppr101.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 130 opcode = 321 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po020~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 130 opcode = 324 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po020~ END
//aid
COPY_EXISTING ~sppr201.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 129 opcode = 321 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po020~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 129 opcode = 324 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po020~ END
//Compatibility
//chant
COPY_EXISTING ~sppr203.spl~ ~override~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po020~ END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po020~ END
//check for FnP Tempus chant
ACTION_IF FILE_EXISTS_IN_GAME ~B_TEM01.spl~ BEGIN
  COPY_EXISTING ~B_TEM01.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po020~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po020~ END
END
//prayer (IWD, IWDIFICATION, MY IWD SPELLS)
//my iWD
ACTION_IF FILE_EXISTS_IN_GAME ~b_IWD.itm~ BEGIN
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_PRAYER~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po020~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po020~ END
COPY_EXISTING ~b_po020.spl~ ~override~
        SAY UNIDENTIFIED_DESC @102000005
	SAY DESC @102000005
END
//IWDIFICATION
ACTION_IF MOD_IS_INSTALLED ~SETUP-IWDIFICATION.TP2~ ~40~ THEN BEGIN
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_PRAYER~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po020~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po020~ END
COPY_EXISTING ~b_po020.spl~ ~override~
        SAY UNIDENTIFIED_DESC @102000005
	SAY DESC @102000005
END
//IWDEE
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
COPY_EXISTING ~SPPR316.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po020~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po020~ END
COPY_EXISTING ~b_po020.spl~ ~override~
        SAY UNIDENTIFIED_DESC @102000005
	SAY DESC @102000005
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Malediction_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Malediction           Added               Acolyte of Tempus: yes                                 Double Checked: no
//                                          IWDEE: yes
//                                          IWDIFICATION: yes
//                                          my IWD spells: yes
//                                          spheres:  I believe so
//                                          SR: Yes (I believe so)

COPY ~spells/data/cantrips/divine/b_po030.spl~ ~override~
        SAY NAME1 @103000000
        SAY NAME2 @103000000
        SAY UNIDENTIFIED_DESC @103000001
	SAY DESC @103000001
COPY ~spells/data/cantrips/divine/b_po031.eff~ ~override~
  SAY 0x1c @103000000 //Malediction
//bless, aid, chant doom
//bless
COPY_EXISTING ~sppr101.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 130 opcode = 321 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 130 opcode = 324 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
//aid
COPY_EXISTING ~sppr201.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 129 opcode = 321 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 129 opcode = 324 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
//chant
COPY_EXISTING ~sppr203.spl~ ~override~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po030~ END
//doom
COPY_EXISTING ~sppr113.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 141 opcode = 321 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 54 opcode = 324 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po030.spl~ ~override~
        SAY UNIDENTIFIED_DESC @103000003
	SAY DESC @103000003
END

//Compatibility
//check for FnP Tempus chant
ACTION_IF FILE_EXISTS_IN_GAME ~B_TEM01.spl~ BEGIN
  COPY_EXISTING ~B_TEM01.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po030~ END
END
//prayer (IWD, IWDIFICATION, MY IWD SPELLS)
//my iWD
ACTION_IF FILE_EXISTS_IN_GAME ~b_IWD.itm~ BEGIN
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_PRAYER~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po030~ END
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CURSE~
  RET spell_res
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po030.spl~ ~override~
        SAY UNIDENTIFIED_DESC @103000004
	SAY DESC @103000004
END

END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = EVAL ~b_po030~ END     //FIrst (hopefully only) clone of 321, so...okay.  May have compatibility issues with other mods
  LPF CLONE_EFFECT INT_VAR match_opcode = 54 opcode = 324 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
COPY_EXISTING ~b_po030.spl~ ~override~
        SAY UNIDENTIFIED_DESC @103000002
	SAY DESC @103000002
END
//IWDIFICATION
ACTION_IF MOD_IS_INSTALLED ~SETUP-IWDIFICATION.TP2~ ~40~ THEN BEGIN
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_PRAYER~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po030~ END
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CURSE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = EVAL ~b_po030~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 54 opcode = 324 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END      
  
COPY_EXISTING ~b_po030.spl~ ~override~
        SAY UNIDENTIFIED_DESC @103000002
	SAY DESC @103000002
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po030.spl~ ~override~
        SAY UNIDENTIFIED_DESC @103000004
	SAY DESC @103000004
END
END
//IWDEE
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
COPY_EXISTING ~SPPR316.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po030~ END

//DO IWD CURSE!
COPY_EXISTING ~b_po020.spl~ ~override~
        SAY UNIDENTIFIED_DESC @102000005
	SAY DESC @102000005
END
//Spell Revisions (Break Enchantment removes Malediction)
ACTION_IF FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN   //any version of sr
COPY_EXISTING ~sppr307.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 221 opcode = 321 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
COPY_EXISTING ~spwi410.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 221 opcode = 321 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po030~ END
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Meditation________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Meditation            Added               Acolyte of Tempus: yes                                 Double Checked: no
//                                          IWDEE: yes
//                                          IWDIFICATION: yes
//                                          my IWD spells: yes
//                                          spheres:  I believe so
//                                          SR: I don't think so
//CHECK SPELL REVISIONS!
//From Charm to Thought for FnP
COPY ~spells/data/cantrips/divine/b_po040.spl~ ~override~
        SAY NAME1 @104000000
        SAY NAME2 @104000000
        SAY UNIDENTIFIED_DESC @104000001
	SAY DESC @104000001
COPY ~spells/data/cantrips/divine/b_po031.eff~ ~override~
  SAY 0x1c @104000002 //meditating
//bless, aid, chant
//bless
COPY_EXISTING ~sppr101.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 130 opcode = 321 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po040~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 130 opcode = 324 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po040~ END
//aid
COPY_EXISTING ~sppr201.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 129 opcode = 321 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po040~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 129 opcode = 324 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po040~ END
//Compatibility
//chant
COPY_EXISTING ~sppr203.spl~ ~override~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po040~ END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po040~ END
//spheres
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po040.spl~ ~override~
        SAY UNIDENTIFIED_DESC @104000004
	SAY DESC @104000004
END

//check for FnP Tempus chant
ACTION_IF FILE_EXISTS_IN_GAME ~B_TEM01.spl~ BEGIN
  COPY_EXISTING ~B_TEM01.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po040~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po040~ END
END

//prayer (IWD, IWDIFICATION, MY IWD SPELLS)
//my iWD
ACTION_IF FILE_EXISTS_IN_GAME ~b_IWD.itm~ BEGIN
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_PRAYER~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po040~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po040~ END
COPY_EXISTING ~b_po040.spl~ ~override~
        SAY UNIDENTIFIED_DESC @104000003
	SAY DESC @104000003
//spheres
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po040.spl~ ~override~
        SAY UNIDENTIFIED_DESC @104000005
	SAY DESC @104000005
END
END
//IWDIFICATION
ACTION_IF MOD_IS_INSTALLED ~SETUP-IWDIFICATION.TP2~ ~40~ THEN BEGIN
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_PRAYER~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po020~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po020~ END
COPY_EXISTING ~b_po040.spl~ ~override~
        SAY UNIDENTIFIED_DESC @104000003
	SAY DESC @104000003
//spheres
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po040.spl~ ~override~
        SAY UNIDENTIFIED_DESC @104000005
	SAY DESC @104000005
END
END
//IWDEE
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
COPY_EXISTING ~SPPR316.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~b_po020~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 parameter1 = 0 parameter2 = 0 timing = 0 duration = 60 STR_VAR resource = EVAL ~b_po020~ END
COPY_EXISTING ~b_po040.spl~ ~override~
        SAY UNIDENTIFIED_DESC @104000003
	SAY DESC @104000003
//spheres
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po040.spl~ ~override~
        SAY UNIDENTIFIED_DESC @104000005
	SAY DESC @104000005
END
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Cause Minor Wounds_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Cause Minor Wounds   Added                Compatiblity                                          Double Checked: no
//                                          My Revised: yes
//                                          Spheres: looks like it
//                                          others?
//ADD SPHERE SYSTEM COMPATIBILITY: SPHERE: Death  d5_spheres.d5
//STANDARD VERSION
//Animation
COPY ~spells/data/cantrips/divine/CLDAMAH.bam~ ~override~
//Sound
COPY ~spells/data/cantrips/divine/#FF_P103.WAV~ ~override~
//icons (placeholders)
COPY ~spells/data/cantrips/divine/SPPR114A.BAM~ ~override~
COPY ~spells/data/cantrips/divine/SPPR114B.BAM~ ~override~
COPY ~spells/data/cantrips/divine/SPPR114C.BAM~ ~override~
//spell itself
COPY ~spells/data/cantrips/divine/b_po050.spl~ ~override~
        SAY NAME1 @105000000
        SAY NAME2 @105000000
        SAY UNIDENTIFIED_DESC @105000001
	SAY DESC @105000001
 LPF ALTER_EFFECT
      INT_VAR match_opcode = 324            //
      STR_VAR resource = EVAL ~b_po050~
  END      //

//Compatibility: sphere system Description: death sphere
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po050.spl~ ~override~
        SAY UNIDENTIFIED_DESC @105000002
	SAY DESC @105000002
END
//Compatibility: altered cure/inflict spells
ACTION_IF FILE_EXISTS_IN_GAME ~b_revise.itm~ BEGIN
COPY_EXISTING ~b_po050.spl~ ~override~
        SAY NAME1 @105000005
        SAY NAME2 @105000005
        SAY UNIDENTIFIED_DESC @105000003
	SAY DESC @101000003
  LPF DELETE_EFFECT INT_VAR match_opcode= 12 END//
  LPF CLONE_EFFECT INT_VAR match_opcode = 215 opcode = 12 parameter1 = 2 parameter2 = 4194304 savingthrow = 0 STR_VAR resource = EVAL ~ ~  END
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 parameter1 = 1 savingthrow = 4 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 215 opcode = 12 parameter1 = 1 parameter2 = 4194304 savingthrow = 0 STR_VAR resource = EVAL ~ ~  END
  LPF CLONE_EFFECT INT_VAR match_opcode = 215 opcode = 12 parameter1 = 5 parameter2 = 4194307 savingthrow = 0 STR_VAR resource = EVAL ~ ~  END
  LPF CLONE_EFFECT INT_VAR match_opcode = 215 opcode = 12 parameter1 = 5 parameter2 = 4194307 savingthrow = 4 STR_VAR resource = EVAL ~ ~  END
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po050.spl~ ~override~
        SAY UNIDENTIFIED_DESC @105000004
	SAY DESC @105000004
END
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Infravision_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Infravision            Added:Yes          Compatiblity:                                         Double Checked: no
//                                          IWDEE: Not needed
//                                          IWDification: Not needed
//                                          My IWD spells: Not needed
//                                          my revised spells: No (may have a 'heat vision' version...)
//                                          spheres: Not needed
//                                          SR: (wiz version will need it) SR may use icons...
//                                          Other: Not needed
COPY ~spells/data/cantrips/divine/b_po060.spl~ ~override~
        SAY NAME1 @106000000
        SAY NAME2 @106000000
        SAY UNIDENTIFIED_DESC @106000001
	SAY DESC @106000001
//Will remove/alter 1st level wiz spell with the mage cantrip version (and/or spell altrations)

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Hold animal____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE: no need
//                                          IWDification: no need
//                                          My IWD spells: no need
//                                          my revised spells: yes
//                                          spheres: no
//                                          SR: Double check v3 improves hold animal (almost certainly does, but...)
//                                          SR: any unique spells dispell hold besides Remove Paralysis?
//                                          Other: no need as far as I can tell
COPY ~spells/data/cantrips/divine/b_po070.spl~ ~override~
        SAY NAME1 @107000000
        SAY NAME2 @107000000
        SAY UNIDENTIFIED_DESC @107000001
	SAY DESC @107000001

ACTION_IF NOT FILE_EXISTS_IN_GAME ~b_revise.itm~ BEGIN   //If Altered hold beast is in game, don't make 3rd level spell unavailable to priests
//not installed if SR is installed                                              NEED TO CHECK V3!
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN
COPY ~spells/data/cantrips/divine/SPPR305.spl~ ~override~ //unmemorizable spell
END
END
//not installed if SRv4 is installed (with or without my revision)               NEED TO CHECK V3!
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN
COPY ~spells/data/cantrips/divine/SPPR305.spl~ ~override~ //unmemorizable spell
END


/* TO BE ADDED
COPY ~clchng/Arcane/Cantrip/Spells/b_wc101.spl~ ~override~
  SAY NAME1 @105000 // Fire Bolt
  SAY UNIDENTIFIED_DESC @105001

COPY ~clchng/Arcane/Cantrip/Spells/b_wc102.spl~ ~override~
  SAY NAME1 @105002 //Acid Splash (Cantrip)
  SAY UNIDENTIFIED_DESC @105003
  
COPY ~clchng/Arcane/Cantrip/Spells/b_wc103.spl~ ~override~
  SAY NAME1 @105004 //Cold Ray (Cantrip)
  SAY UNIDENTIFIED_DESC @105005
  
COPY ~clchng/Arcane/Cantrip/Spells/b_wc104.spl~ ~override~
  SAY NAME1 @105006 //Shocking Grasp (Cantrip)
  SAY UNIDENTIFIED_DESC @105007

COPY ~clchng/Arcane/Cantrip/Itm/sgrasp.itm~ ~override~

COPY ~clchng/Arcane/Cantrip/Spells/b_wc105.spl~ ~override~
  SAY NAME1 @105008//Infravision (Cantrip)
  SAY UNIDENTIFIED_DESC @105009
  
COPY ~clchng/Arcane/Cantrip/Spells/b_wc106.spl~ ~override~
  SAY NAME1 @105010//Friends (Cantrip)
  SAY UNIDENTIFIED_DESC @105011

COPY ~clchng/Arcane/Cantrip/Spells/b_wc107.spl~ ~override~
  SAY NAME1 @105012//Chill Touch (Cantrip)
  SAY UNIDENTIFIED_DESC @105013

@105000 = ~Fire Bolt (Cantrip)~
@105001 = ~Fire Bolt (Cantrip)
Level: Cantrip
School: Evocation
Range: Long
Duration: Instant
Casting Time: 3
Area of Effect: 1 creature
Saving Throw: Breath +2

When this cantrip is cast, the caster shoots a bolt of fire from his hand at the target of his choosing causing 1d6 points of fire damage on a sucessful hit.  A creature may make a save vs breath +2 to avoid being damaged by this spell~

@105002 = ~Acid Splash (Cantrip)~
@105003 = ~Acid Splash (Cantrip)
Level: Cantrip
School: Conjuration
Range: Long
Duration: 1 round
Casting Time: 3
Area of Effect: 1 creature
Saving Throw: Breath +2

When this cantrip is cast, the caster conjurs a ball of acid and hurls it towards his target causing 1d3 acid damage on a successful hit on the first round, and an additional 1d3 points of damage one round later.  A creature may make a save vs breath +2 to avoid being damaged by this spell~

@105004 = ~Frost Ray (Cantrip)~
@105005 = ~Frost Ray (Cantrip)
Level: Cantrip
School: Evocation
Range: Long
Duration: Instant
Casting Time: 3
Area of Effect: 1 creature
Saving Throw: Breath +2

When this cantrip is cast, the caster shoots a fay of frost from his hand at the target of his choosing causing 1d6 points of cold damage on a sucessful hit.  A creature may make a save vs breath +2 to avoid being damaged by this spell~


@105006 = ~Shocking Grasp (Cantrip)~
@105007 = ~Shocking Grasp (Cantrip)
Level: Cantrip
School: Alteration
Range: Touch
Duration: 1 round (special)
Casting Time: 1
Area of Effect: 1 creature
Saving Throw: None

When the wizard touches a creature while this cantrip is in effect, an electrical charge will deal 1d8 points of damage to the creature touched. In addition, the grasp itself does 1d2 fist damage (Strength bonuses apply). The wizard only has one charge, and once an opponent has been touched, the spell's energies have been used. If the wizard misses, the spell is wasted.~

@105008 = ~Infravision (Cantrip)~
@105009 = ~Infravision (Cantrip)
Level: Cantrip
School: General
Range: 30 ft.
Duration: 2 hours
Casting Time: 1
Area of Effect: 1 creature
Saving Throw: None

Upon the casting of this spell the recipient gains the ability to see with infravision, just as an elf or a dwarf would. This effect lasts for the duration of the spell or until dispelled.~

@105010 = ~Friends (Cantrip)~
@105011 = ~Friends (Cantrip)
Level: Cantrip
School: Enchantment
Range: 0
Duration: 10 rounds
Casting Time: 1
Area of Effect: The caster
Saving Throw: None

A Friends spell causes the wizard to temporarily gain 6 points of Charisma. Those who view the caster tend to be very impressed with <PRO_HIMHER> and make an effort to be <PRO_HISHER> friends and help <PRO_HIMHER>, as appropriate to the situation. Officious bureaucrats might decide to become helpful; surly gate guards might wax informative; attacking orcs might spare the caster's life, taking <PRO_HIMHER> captive instead.~

@105012 = ~Chill Touch (Cantrip)~
@105013 = ~Chill Touch (Cantrip)
Level: Cantrip
School: Necromancy
Range: 0
Duration: 1 round
Casting Time: 1
Area of Effect: The creature
Saving Throw: Neg.

When the caster completes this spell, a blue glow encompasses <PRO_HISHER> hand. This energy attacks the life force of any living creature upon which the wizard makes a successful melee attack. (Nonliving creatures such as golems and undead are unaffected by this spell.) The creature is punched for 1d2 fist damage (Strength bonuses apply) and must make a Saving Throw vs. Spell or suffer 1d8 points of damage and receive a -2 THAC0 penalty for 5 rounds.~


//////////////////////////////////////
////////// SPl, cre,baf,dlg //////////
//////////////////////////////////////

COPY ~clchng/Arcane/Cantrip/Spl/b_csel1.spl~ ~override~
  SAY NAME1 @115259//Prep Cantrip
@115259 = ~Select your cantrips~
//Clearly not all of this is needed...

COPY ~clchng/Arcane/Cantrip/Spl/b_can00.2da~ ~override~

COMPILE ~clchng/Arcane/Cantrip/Baf/b_csel1.baf~ ~override~
COMPILE ~clchng/Arcane/Cantrip/dlg/b_csel1.d~ ~override~

COPY ~clchng/Arcane/Cantrip/cre/b_csel1.cre~ ~override~
//end to be added

ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msred.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msblu.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msgrn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msbrn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msorn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_mswhi.pro~
COPY ~TomeAndBlood/data/cantrips/spmagm02.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm03.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm04.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm05.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm06.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm07.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_cant.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp420.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp710.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp809.bam~ ~override~
//COPY ~TomeAndBlood/data/cantrips/d5_wildm.2da~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_cstbo.spl~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_cstpn.spl~ ~override~
//Choose a cantrip
COPY ~TomeAndBlood/data/cantrips/d5_cantr.spl~ ~override~
	SAY NAME1 @6012
COPY ~TomeAndBlood/data/cantrips/d5_cant.spl~ ~override~
	SAY NAME1 @6012
	SAY UNIDENTIFIED_DESC @6013
COPY ~TomeAndBlood/data/cantrips/d5_cant1.spl~ ~override~
	SAY NAME1 @6012
	SAY UNIDENTIFIED_DESC @6013
COPY ~TomeAndBlood/data/cantrips/d5_cant2.spl~ ~override~
	SAY NAME1 @6012
	SAY UNIDENTIFIED_DESC @6013
COPY ~TomeAndBlood/data/cantrips/d5_cant3.spl~ ~override~
	SAY NAME1 @6012
	SAY UNIDENTIFIED_DESC @6013
COPY ~TomeAndBlood/data/cantrips/d5_cantr.2da~ ~override~
//abjurer cantrip: protective shell
COPY ~TomeAndBlood/data/cantrips/d5_maab.spl~ ~override~
	SAY NAME1 @6014
	SAY UNIDENTIFIED_DESC @6015
COPY ~TomeAndBlood/data/cantrips/d5_wiab.spl~ ~override~
	SAY NAME1 @6014
	SAY UNIDENTIFIED_DESC @6015
//conjurer cantrip: summon rabbit	
COPY ~TomeAndBlood/data/cantrips/d5_maco.spl~ ~override~
	SAY NAME1 @6016
	SAY UNIDENTIFIED_DESC @6017
COPY ~TomeAndBlood/data/cantrips/d5_wico.spl~ ~override~
	SAY NAME1 @6016
	SAY UNIDENTIFIED_DESC @6017
COPY ~TomeAndBlood/data/cantrips/d5_rabb.cre~ ~override~
	SAY NAME1 @6018
//diviner cantrip: anticipation
COPY ~TomeAndBlood/data/cantrips/d5_madi.spl~ ~override~
	SAY NAME1 @6019
	SAY UNIDENTIFIED_DESC @6020
COPY ~TomeAndBlood/data/cantrips/d5_widi.spl~ ~override~
	SAY NAME1 @6019
	SAY UNIDENTIFIED_DESC @6020
//enchanter cantrip: drowse
COPY ~TomeAndBlood/data/cantrips/d5_maen.spl~ ~override~
	SAY NAME1 @6021
	SAY UNIDENTIFIED_DESC @6022
COPY ~TomeAndBlood/data/cantrips/d5_wien.spl~ ~override~
	SAY NAME1 @6021
	SAY UNIDENTIFIED_DESC @6022
//illusionist cantrip: bedazzle
COPY ~TomeAndBlood/data/cantrips/d5_mail.spl~ ~override~
	SAY NAME1 @6023
	SAY UNIDENTIFIED_DESC @6024
COPY ~TomeAndBlood/data/cantrips/d5_wiil.spl~ ~override~
	SAY NAME1 @6023
	SAY UNIDENTIFIED_DESC @6024
//invoker cantrip: magic bolt
COPY ~TomeAndBlood/data/cantrips/d5_main.spl~ ~override~
	SAY NAME1 @6025
	SAY UNIDENTIFIED_DESC @6026
	WRITE_SHORT 0x098 ~%d5_msred%~
COPY ~TomeAndBlood/data/cantrips/d5_wiin.spl~ ~override~
	SAY NAME1 @6025
	SAY UNIDENTIFIED_DESC @6026
	WRITE_SHORT 0x098 ~%d5_msred%~
//necromancer cantrip: stiffen bones
COPY ~TomeAndBlood/data/cantrips/d5_mane.spl~ ~override~
	SAY NAME1 @6027
	SAY UNIDENTIFIED_DESC @6028
COPY ~TomeAndBlood/data/cantrips/d5_wine.spl~ ~override~
	SAY NAME1 @6027
	SAY UNIDENTIFIED_DESC @6028
//transmuter cantrip: earthen grasp
COPY ~TomeAndBlood/data/cantrips/d5_matr.spl~ ~override~
	SAY NAME1 @6029
	SAY UNIDENTIFIED_DESC @6030
COPY ~TomeAndBlood/data/cantrips/d5_witr.spl~ ~override~
	SAY NAME1 @6029
	SAY UNIDENTIFIED_DESC @6030
//fire bolt
COPY ~TomeAndBlood/data/cantrips/d5_mfir.spl~ ~override~
	SAY NAME1 @6031
	SAY UNIDENTIFIED_DESC @6032
COPY ~TomeAndBlood/data/cantrips/d5_wfir.spl~ ~override~
	SAY NAME1 @6031
	SAY UNIDENTIFIED_DESC @6032
	WRITE_SHORT 0x098 ~%d5_msorn%~
//ice bolt
COPY ~TomeAndBlood/data/cantrips/d5_mcld.spl~ ~override~
	SAY NAME1 @6033
	SAY UNIDENTIFIED_DESC @6034
COPY ~TomeAndBlood/data/cantrips/d5_wcld.spl~ ~override~
	SAY NAME1 @6033
	SAY UNIDENTIFIED_DESC @6034
	WRITE_SHORT 0x098 ~%d5_mswhi%~
//acid bolt
COPY ~TomeAndBlood/data/cantrips/d5_macd.spl~ ~override~
	SAY NAME1 @6035
	SAY UNIDENTIFIED_DESC @6036
COPY ~TomeAndBlood/data/cantrips/d5_wacd.spl~ ~override~
	SAY NAME1 @6035
	SAY UNIDENTIFIED_DESC @6036
	WRITE_SHORT 0x098 ~%d5_msgrn%~
//electric bolt
COPY ~TomeAndBlood/data/cantrips/d5_melc.spl~ ~override~
	SAY NAME1 @6037
	SAY UNIDENTIFIED_DESC @6038
COPY ~TomeAndBlood/data/cantrips/d5_welc.spl~ ~override~
	SAY NAME1 @6037
	SAY UNIDENTIFIED_DESC @6038
	WRITE_SHORT 0x098 ~%d5_msblu%~
//earth bolt
COPY ~TomeAndBlood/data/cantrips/d5_wert.spl~ ~override~
	SAY NAME1 @6039
	SAY UNIDENTIFIED_DESC @6040
	WRITE_SHORT 0x098 ~%d5_msbrn%~
//shield spell now protects against cantrips
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_maab~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wiab~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_maen~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wien~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_main~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wiin~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_mail~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wiil~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_mane~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wine~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_madi~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_widi~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_matr~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_witr~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_maco~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wico~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wfir~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_welc~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wcld~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wacd~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wert~ END
	BUT_ONLY 
	
//adding cantrips to appropriate mages
APPEND ~CLABMA01.2da~ ~CANTRIPS GA_D5_CANT1 ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 

APPEND ~CLABMA02.2da~ ~CANTRIPS GA_D5_WIAB ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

APPEND ~CLABMA03.2da~ ~CANTRIPS GA_D5_WINE ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

APPEND ~CLABMA04.2da~ ~CANTRIPS GA_D5_WITR ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 

APPEND ~CLABMA05.2da~ ~CANTRIPS GA_D5_WIDI ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 

APPEND ~CLABMA06.2da~ ~CANTRIPS GA_D5_WICO ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 

APPEND ~CLABMA07.2da~ ~CANTRIPS GA_D5_WIIN ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

APPEND ~CLABMA08.2da~ ~CANTRIPS GA_D5_WIIL ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 

APPEND ~CLABMA09.2da~ ~CANTRIPS GA_D5_WIEN ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
		
APPEND ~CLABSO01.2da~ ~CANTRIPS GA_D5_WFIR ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~		

//updating descriptions
//9563
	ACTION_GET_STRREF 9563 mage
	OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
	  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
	END
	STRING_SET_EVALUATE 9563 ~%mage%~
	//17245
	ACTION_GET_STRREF 17245 mage
	OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
	  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
	END
	STRING_SET_EVALUATE 17245 ~%mage%~
	//9564: abjurer
		ACTION_GET_STRREF 9564 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Protective Shell cantrip.~
		END
		STRING_SET_EVALUATE 9564 ~%mage%~
		//9565: conjurer
		ACTION_GET_STRREF 9565 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Conjure Rabbit cantrip.~
		END
		STRING_SET_EVALUATE 9565 ~%mage%~
		//9566: diviner
		ACTION_GET_STRREF 9566 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Anticipation cantrip.~
		END
		STRING_SET_EVALUATE 9566 ~%mage%~
		//9567: enchanter
		ACTION_GET_STRREF 9567 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Drowse cantrip.~
		END
		STRING_SET_EVALUATE 9567 ~%mage%~
		//9568: illusionist
		ACTION_GET_STRREF 9568 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Bedazzle cantrip.~
		END
		STRING_SET_EVALUATE 9568 ~%mage%~
		//9569: invoker
		ACTION_GET_STRREF 9569 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Magic Bolt cantrip.~
		END
		STRING_SET_EVALUATE 9569 ~%mage%~
		//9570: necromancer
		ACTION_GET_STRREF 9570 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Stiffen Bones cantrip.~
		END
		STRING_SET_EVALUATE 9570 ~%mage%~
		//9571: transmuter
		ACTION_GET_STRREF 9571 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Earthen Grasp cantrip.~
		END
		STRING_SET_EVALUATE 9571 ~%mage%~
//bgee	
	ACTION_IF GAME_IS ~bgee~ THEN BEGIN 
		//24233
		ACTION_GET_STRREF 24233 sorcerer
		OUTER_PATCH_SAVE sorcerer ~%sorcerer%~ BEGIN
		  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
		END
		STRING_SET_EVALUATE 24233 ~%sorcerer%~
	END
//bg2ee
	ACTION_IF GAME_IS ~bg2ee~ THEN BEGIN 
		//45866
		ACTION_GET_STRREF 45866 sorcerer
		OUTER_PATCH_SAVE sorcerer ~%sorcerer%~ BEGIN
			REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
		END
		STRING_SET_EVALUATE 45866 ~%sorcerer%~
	END 
//bgee and bg2ee
ACTION_IF GAME_IS ~bgee bg2ee~ THEN BEGIN 
		//24290: abjurer
		ACTION_GET_STRREF 24290 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Protective Shell cantrip.~
		END
		STRING_SET_EVALUATE 24290 ~%mage%~
		//24291: conjurer
		ACTION_GET_STRREF 24291 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Conjure Rabbit cantrip.~
		END
		STRING_SET_EVALUATE 24291 ~%mage%~
		//24292: diviner
		ACTION_GET_STRREF 24292 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Anticipation cantrip.~
		END
		STRING_SET_EVALUATE 24292 ~%mage%~
		//24293: enchanter
		ACTION_GET_STRREF 24293 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Drowse cantrip.~
		END
		STRING_SET_EVALUATE 24293 ~%mage%~
		//24294: illusionist
		ACTION_GET_STRREF 24294 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Bedazzle cantrip.~
		END
		STRING_SET_EVALUATE 24294 ~%mage%~
		//24295: invoker
		ACTION_GET_STRREF 24295 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Magic Bolt cantrip.~
		END
		STRING_SET_EVALUATE 24295 ~%mage%~
		//24296: necromancer
		ACTION_GET_STRREF 24296 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Stiffen Bones cantrip.~
		END
		STRING_SET_EVALUATE 24296 ~%mage%~
		//24297: transmuter
		ACTION_GET_STRREF 24297 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Earthen Grasp cantrip.~
		END
		STRING_SET_EVALUATE 24297 ~%mage%~
END 
//iwdee
	ACTION_IF GAME_IS ~iwdee~ THEN BEGIN 
		//37189
		ACTION_GET_STRREF 37189 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
		  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
		END
		STRING_SET_EVALUATE 37189 ~%mage%~
		//34605
		ACTION_GET_STRREF 34605 sorcerer
		OUTER_PATCH_SAVE sorcerer ~%sorcerer%~ BEGIN
		  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip at 1st level. ~
		END
		STRING_SET_EVALUATE 34605 ~%sorcerer%~
		//37249
		ACTION_GET_STRREF 37249 sorcerer
		OUTER_PATCH_SAVE sorcerer ~%sorcerer%~ BEGIN
		  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
		END
		STRING_SET_EVALUATE 37249 ~%sorcerer%~
//37193: abjurer
		ACTION_GET_STRREF 37193 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Protective Shell cantrip.~
		END
		STRING_SET_EVALUATE 37193 ~%mage%~
		//37196: conjurer
		ACTION_GET_STRREF 37196 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Conjure Rabbit cantrip.~
		END
		STRING_SET_EVALUATE 37196 ~%mage%~
		//37199: diviner
		ACTION_GET_STRREF 37199 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Anticipation cantrip.~
		END
		STRING_SET_EVALUATE 37199 ~%mage%~
		//37202: enchanter
		ACTION_GET_STRREF 37202 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Drowse cantrip.~
		END
		STRING_SET_EVALUATE 37202 ~%mage%~
		//37205: illusionist
		ACTION_GET_STRREF 37205 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Bedazzle cantrip.~
		END
		STRING_SET_EVALUATE 37205 ~%mage%~
		//37208: invoker
		ACTION_GET_STRREF 37208 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Magic Bolt cantrip.~
		END
		STRING_SET_EVALUATE 37208 ~%mage%~
		//37211: necromancer
		ACTION_GET_STRREF 37211 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Stiffen Bones cantrip.~
		END
		STRING_SET_EVALUATE 37211 ~%mage%~
		//37214: transmuter
		ACTION_GET_STRREF 37214 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Earthen Grasp cantrip.~
		END
		STRING_SET_EVALUATE 37214 ~%mage%~
END 

OUTER_SET strref = (0 - 1)

COPY_EXISTING - ~kitlist.2da~ ~override~
	COUNT_2DA_COLS num_cols
		READ_2DA_ENTRIES_NOW ~r2en_kitlist~ num_cols
		FOR (row = 1; row < r2en_kitlist; row += 1) BEGIN
			READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 1 kitname
			PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~DRAGON_DISCIPLE~) BEGIN
			  READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 4 strref
			END
		  END
		ACTION_IF (strref >= 0) BEGIN
		  ACTION_GET_STRREF strref dd
		  OUTER_PATCH_SAVE dd ~%dd%~ BEGIN
			REPLACE_TEXTUALLY CASE_SENSITIVE ~Advantages:~ ~Advantages:
– May use the Fire Bolt cantrip.~
		END
		STRING_SET_EVALUATE strref ~%dd%~
		END 		
				  
*/				  
				  
				  
				  
				  
				  