////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
/////////////////////////////////////             REVISED SPELLS               //////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
/////////////////////////////////////         CANTRIP COMPATIBILITY           //////////////////////////////////////
/////////////////////////////////////                                         //////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//MOVE SPELLS FROM 'NEW SPELLS' TO 'REVISED SPELLS' SPECIFICALLY 'REMOVE FATIGUE' DONE

//SR Cause wounds spells summon a magic item that does the damage.  Account for this
//Make compatible with sphere (if installed after them)

// START FROM THE BEGINNING.  USE REPLACE_TEXTUALLY WITH TRA
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________Cure minor wounds__________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

ACTION_IF FILE_EXISTS_IN_GAME ~b_cant.itm~ BEGIN   //If Cure Minor Wounds is installed
COPY_EXISTING ~b_po010.spl~ ~override~      //description
 SPRINT old @101000004//old text
 SPRINT new @101000005//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //Change to 10% +1 HP
  LPF ALTER_EFFECT INT_VAR match_opcode = 17  parameter1 = 1 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 17 parameter1 = 10 parameter2 = 2 END
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________cause/inflict minor wounds_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


ACTION_IF FILE_EXISTS_IN_GAME ~b_cant.itm~ BEGIN
COPY_EXISTING ~b_po050.spl~ ~override~
 SPRINT old @105000003//old text
 SPRINT new @105000004//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old with new (set damage to % of target's hp)
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //
  LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 1 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 match_savingthrow = 0 parameter1 = 5 parameter2 = 4194307 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 match_savingthrow = 1 parameter1 = 5 parameter2 = 4194307 savingthrow = 4 END
END

//Continue from here
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Infravision_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Only install if cantrips is installed
ACTION_IF FILE_EXISTS_IN_GAME ~b_cant.itm~ BEGIN
COPY ~spells/data/cantrips/divine/b_po060.spl~ ~override~
        SAY NAME1 @106000000
        SAY NAME2 @106000000
        SAY UNIDENTIFIED_DESC @106000001
	SAY DESC @106000001
//spheres
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
COPY_EXISTING ~b_po060.spl~ ~override~
 SPRINT old @106000002//old text
 SPRINT new @106000003//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old with new (charm to thought sphere)
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //
END

END





//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________Hold Animal ---> Hold Beast____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


//FIND ALL VERSIONS OF THIS SPELL!
//'BRUTING' it because there are different versions of the spell in different versions of the game.  (may 'do it right', however).  
//REMOVE FROM SPHERES TPA
COPY ~Spells/data/spells/revised_spells/hold_animal/#GENENCH.vvc~ ~override~ // vvc
COPY ~Spells/data/spells/revised_spells/hold_animal/ENCHANX.bam~ ~override~ // vvc bam
COPY ~Spells/data/spells/revised_spells/hold_animal/#ARE_P21.WAV~ ~override~ // vvc sound
COPY ~Spells/data/spells/revised_spells/hold_animal/#EFF_P04.WAV~ ~override~ // sound
COPY ~Spells/data/spells/revised_spells/hold_animal/#EFF_E05.WAV~ ~override~ // sound
ADD_PROJECTILE ~Spells/data/spells/revised_spells/hold_animal/b_beast.pro~   //pro
COPY ~Spells/data/spells/revised_spells/hold_animal/sppr305.spl~ ~override~ // Hold Beast
        SAY NAME1 @51104
        SAY NAME2 @51104
        SAY UNIDENTIFIED_DESC @51105
	SAY DESC @51105
	WRITE_SHORT 0x098 ~%b_beast%~
	WRITE_SHORT 0x0C0 ~%b_beast%~
	WRITE_SHORT 0x0E8 ~%b_beast%~
	WRITE_SHORT 0x110 ~%b_beast%~
	WRITE_SHORT 0x138 ~%b_beast%~
	WRITE_SHORT 0x160 ~%b_beast%~
	WRITE_SHORT 0x188 ~%b_beast%~
	WRITE_SHORT 0x1B0 ~%b_beast%~
	WRITE_SHORT 0x1D8 ~%b_beast%~
	WRITE_SHORT 0x200 ~%b_beast%~
	WRITE_SHORT 0x228 ~%b_beast%~
	WRITE_SHORT 0x250 ~%b_beast%~
	WRITE_SHORT 0x278 ~%b_beast%~
	WRITE_SHORT 0x2A0 ~%b_beast%~
	WRITE_SHORT 0x2C8 ~%b_beast%~
	WRITE_SHORT 0x2F0 ~%b_beast%~
//MAKING 'ALLIES' IMMUNE.  nOT SURE IF THAT MEANS 'ALLY TO PC' OR 'ALLY TO CASTER'.
//I THIK IT'S 'ALLIES TO PC' SO MAY NEED A DIFFERENT VERSION FOR PCS VS NPCS.
//ORIGINAL MAY NEED TO BE ADDED TO HIDESPL, AND MADE INTO A NPC VERSION, SCRIPTS SHOULD BE TWEAKED SO THEY USE VS. SUMMONED MONSTERS
//THIS VERSION WOULD BE ADDSPELLED AND GIVEN TO PC'S, BUT NOT IF SPELL REVISONS IS INSTALLED

//ALSO, DOUBLE CHECK THIS DOESN'T HOLD SPIRIT SUMMONS

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________Cure Light Wound 20%___________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


//Find all versions, including 'innate' versions, of cure light wounds (sppr103/spin101 present in both bgee and bg2ee, no spin101 in IWDEE)
//cures an additional 4 hit points so it's still useful at lower levels
COPY_EXISTING ~sppr103.spl~ ~override~ //
        SAY UNIDENTIFIED_DESC @50101
	SAY DESC @50101
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 17            //
            parameter1 = 4
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 17 parameter1 = 20 parameter2 = 2 END

ACTION_IF FILE_EXISTS_IN_GAME ~spin101.spl~ BEGIN
COPY_EXISTING ~spin101.spl~ ~override~ //
        SAY UNIDENTIFIED_DESC @50101
	SAY DESC @50101
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 17            //
            parameter1 = 4
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 17 parameter1 = 20 parameter2 = 2 END
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________cure moderate wound 30%________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_____________________________________________________________________________________________
//Only exists in IWDEE, or if IWD spells mod (or IWDIFICATION, presumably) is installed

//Check iwdification!
//Check SR!

ACTION_IF FILE_EXISTS_IN_GAME ~b_IWD.itm~ BEGIN
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CURE_MODERATE_WOUNDS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
        SAY UNIDENTIFIED_DESC @50102
	SAY DESC @50102
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 17            //
                  parameter1 = 6
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 17 parameter1 = 30 parameter2 = 2 END
END

ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CURE_MODERATE_WOUNDS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
        SAY UNIDENTIFIED_DESC @50102
	SAY DESC @50102
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 17            //
                  parameter1 = 6
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 17 parameter1 = 30 parameter2 = 2 END
END

ACTION_IF MOD_IS_INSTALLED ~SETUP-IWDIFICATION.TP2~ ~40~ THEN BEGIN
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CURE_MODERATE_WOUNDS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
        SAY UNIDENTIFIED_DESC @50102
	SAY DESC @50102
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 17            //
                  parameter1 = 6
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 17 parameter1 = 30 parameter2 = 2 END
END


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________cure med wound 40%_____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//

COPY_EXISTING ~SPPR315.spl~ ~override~
        SAY UNIDENTIFIED_DESC @50103
	SAY DESC @50103
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 17            //
                  parameter1 = 8
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 17 parameter1 = 40 parameter2 = 2 END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_____________________________________________________cure serious wound 50%___________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
COPY_EXISTING ~SPPR401.spl~ ~override~
        SAY UNIDENTIFIED_DESC @50104
	SAY DESC @50104
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 17            //
                  parameter1 = 10
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 17 parameter1 = 50 parameter2 = 2 END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_____________________________________________________cure critical wound 60%__________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
COPY_EXISTING ~SPPR502.spl~ ~override~
        SAY UNIDENTIFIED_DESC @50105
	SAY DESC @50105
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 17            //
                  parameter1 = 12
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 17 parameter1 = 60 parameter2 = 2 END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________mass cure 25% +6 hp____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


COPY_EXISTING ~SPPR514.spl~ ~override~
        SAY UNIDENTIFIED_DESC @50106
	SAY DESC @50106
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 17            //
                  parameter1 = 6
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 17 parameter1 = 25 parameter2 = 2 END
 //change name of spell if IWD
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
COPY_EXISTING ~SPPR514.spl~ ~override~
        SAY NAME1 @50107
        SAY NAME2 @50107
END


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//______________________________________________________Inflict Light Wounds 20%_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Only exists in IWDEE, or if IWD spells mod (or IWDIFICATION, presumably) is installed

//Check iwdification!
//Check SR!

ACTION_IF FILE_EXISTS_IN_GAME ~b_IWD.itm~ BEGIN
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CAUSE_LIGHT_WOUNDS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
        SAY UNIDENTIFIED_DESC @11400003
	SAY DESC @11400003
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 12            //
                  parameter1 = 3
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 parameter1 = 10 parameter2 = 4194307 END
END

ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CAUSE_LIGHT_WOUNDS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
        SAY UNIDENTIFIED_DESC @11400003
	SAY DESC @11400003
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 12            //
                  parameter1 = 3
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 parameter1 = 10 parameter2 = 4194307 END
END

ACTION_IF MOD_IS_INSTALLED ~SETUP-IWDIFICATION.TP2~ ~40~ THEN BEGIN
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_CAUSE_LIGHT_WOUNDS~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
        SAY UNIDENTIFIED_DESC @11400003
	SAY DESC @11400003
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 12            //
                  parameter1 = 3
  END      //
  LPF CLONE_EFFECT INT_VAR match_opcode = 12 parameter1 = 10 parameter2 = 4194307 END
END


//Altered Inflict/harm spells  (CHANGE NAME FROM 'CAUSE x' To 'Inflict x'
//ACTION_IF FILE_EXISTS_IN_GAME ~b_po050.spl~ BEGIN

//Goodberries and fatigue 'revision'
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________Remove Fatigue_________________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

ADD_SPELL ~Spells/data/revised_spells/unfailing_endurance/b_p101.spl~ 1 1 ~CLERIC_REMOVE_FATIGUE~ //
        SAY NAME1 @10100000
        SAY NAME2 @10100000
        SAY UNIDENTIFIED_DESC @10100001
	SAY DESC @10100001
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_REMOVE_FATIGUE~
  RET spell_res
END
//icons
COPY ~Spells/data/revised_spells/unfailing_endurance/SPPR424a.bam~ ~override/%spell_res%a.bam~
COPY ~Spells/data/revised_spells/unfailing_endurance/SPPR424b.bam~ ~override/%spell_res%b.bam~
COPY ~Spells/data/revised_spells/unfailing_endurance/SPPR424c.bam~ ~override/%spell_res%c.bam~
//add bams to spl
COPY_EXISTING ~%spell_res%.spl~ ~override~
  WRITE_EVALUATED_ASCII 0x003a ~%spell_res%C~
  WRITE_EVALUATED_ASCII 0x0076 ~%spell_res%B~

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________Unfailing Endurance____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//REMOVE UNFAILING ENDURANCE FROM SELECTION IF NO IWDEE SPELLS INSTALLED
//WHAT DOES THE BELOW CODE DO, EXACTLY?  DOCUMENTATION!!!

//IDEAS:
//DURATIoN WHERE CHARACTER DOES NOT EXPERIENCE ANY FATIGUE (e.g. from haste)
//CAST ON TOTAL PARTY
//Heals?  

//IMPROVED 'MY' VERSION
ACTION_IF FILE_EXISTS_IN_GAME ~b_IWD.itm~ BEGIN
//should be able to use exact same code for iwdee and iwdification
//spec ability
COPY ~Spells/data/revised_spells/unfailing_endurance/b_fatig.spl~ ~override~
        SAY NAME1 @10100000
        SAY NAME2 @10100000
        SAY UNIDENTIFIED_DESC @10100004
	SAY DESC @10100004
//heal notification
COPY ~Spells/data/revised_spells/unfailing_endurance/B_HEALN.eff~ ~override~
  SAY 0x1c ~Healed~ //healed (already in dialog.tlk so...)

//animation
COPY ~Spells/data/revised_spells/unfailing_endurance/ENCHAH.bam~ ~override~

LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_UNFAILING_ENDURANCE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
        SAY NAME1 @10100002
        SAY NAME2 @10100002
        SAY UNIDENTIFIED_DESC @10100003
	SAY DESC @10100003
	WRITE_BYTE 0x072 ~2~  //Projectile
	WRITE_BYTE 0x07E ~5~  //Self
	WRITE_SHORT 0x098 ~158~  //DH Projectile
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 324 parameter1 = 0 parameter2 = 1 STR_VAR resource = EVAL ~%spell_res%~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 321 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~%spell_res%~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 17 parameter1 = 10 parameter2 = 2 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 171 timing = 0 parameter1 = 0 parameter2 = 0 duration = 2400 STR_VAR resource = EVAL ~b_fatig~  END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 172 timing = 4 parameter1 = 0 parameter2 = 0 duration = 2400 STR_VAR resource = EVAL ~b_fatig~  END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 177 parameter1 = 0 parameter2 = 2 STR_VAR resource = EVAL ~b_healn~ END
  LPF ALTER_EFFECT INT_VAR match_opcode = 215 STR_VAR resource = EVAL ~ENCHAH~  END
END

//IWDEE

ACTION_IF GAME_IS ~iwdee~ THEN BEGIN   //
//should be able to use exact same code for iwdee and iwdification
//spec ability
COPY ~Spells/data/revised_spells/unfailing_endurance/b_fatig.spl~ ~override~
        SAY NAME1 @10100000
        SAY NAME2 @10100000
        SAY UNIDENTIFIED_DESC @10100004
	SAY DESC @10100004
//heal notification
COPY ~Spells/data/revised_spells/unfailing_endurance/B_HEALN.eff~ ~override~
  SAY 0x1c ~Healed~ //healed (already in dialog.tlk so...)

//animation
COPY ~Spells/data/revised_spells/unfailing_endurance/ENCHAH.bam~ ~override~

LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_UNFAILING_ENDURANCE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
        SAY NAME1 @10100002
        SAY NAME2 @10100002
        SAY UNIDENTIFIED_DESC @10100003
	SAY DESC @10100003
	WRITE_BYTE 0x072 ~2~  //Projectile
	WRITE_BYTE 0x07E ~5~  //Self
	WRITE_SHORT 0x098 ~158~  //DH Projectile
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 324 parameter1 = 0 parameter2 = 1 STR_VAR resource = EVAL ~%spell_res%~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 321 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~%spell_res%~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 17 parameter1 = 10 parameter2 = 2 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 171 timing = 0 parameter1 = 0 parameter2 = 0 duration = 2400 STR_VAR resource = EVAL ~b_fatig~  END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 172 timing = 4 parameter1 = 0 parameter2 = 0 duration = 2400 STR_VAR resource = EVAL ~b_fatig~  END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 177 parameter1 = 0 parameter2 = 2 STR_VAR resource = EVAL ~b_healn~ END
  LPF ALTER_EFFECT INT_VAR match_opcode = 215 STR_VAR resource = EVAL ~ENCHAH~  END
END
//IWDIfication
ACTION_IF MOD_IS_INSTALLED ~SETUP-IWDIFICATION.TP2~ ~40~ THEN BEGIN//should be able to use exact same code for iwdee and iwdification
//spec ability
COPY ~Spells/data/revised_spells/unfailing_endurance/b_fatig.spl~ ~override~
        SAY NAME1 @10100000
        SAY NAME2 @10100000
        SAY UNIDENTIFIED_DESC @10100004
	SAY DESC @10100004
//heal notification
COPY ~Spells/data/revised_spells/unfailing_endurance/B_HEALN.eff~ ~override~
  SAY 0x1c ~Healed~ //healed (already in dialog.tlk so...)

//animation
COPY ~Spells/data/revised_spells/unfailing_endurance/ENCHAH.bam~ ~override~

LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_UNFAILING_ENDURANCE~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
        SAY NAME1 @10100002
        SAY NAME2 @10100002
        SAY UNIDENTIFIED_DESC @10100003
	SAY DESC @10100003
	WRITE_BYTE 0x072 ~2~  //Projectile
	WRITE_BYTE 0x07E ~5~  //Self
	WRITE_SHORT 0x098 ~158~  //DH Projectile
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 324 parameter1 = 0 parameter2 = 1 STR_VAR resource = EVAL ~%spell_res%~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 321 parameter1 = 0 parameter2 = 0 STR_VAR resource = EVAL ~%spell_res%~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 17 parameter1 = 10 parameter2 = 2 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 171 timing = 0 parameter1 = 0 parameter2 = 0 duration = 2400 STR_VAR resource = EVAL ~b_fatig~  END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 172 timing = 4 parameter1 = 0 parameter2 = 0 duration = 2400 STR_VAR resource = EVAL ~b_fatig~  END
  LPF CLONE_EFFECT INT_VAR match_opcode = 93 opcode = 177 parameter1 = 0 parameter2 = 2 STR_VAR resource = EVAL ~b_healn~ END
  LPF ALTER_EFFECT INT_VAR match_opcode = 215 STR_VAR resource = EVAL ~ENCHAH~  END
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Goodberry____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//revised goodberries
COPY ~Spells/data/spells/revised_spells/goodberry/GBERRY.itm~ ~override~ // revised berries
        SAY UNIDENTIFIED_DESC @51408
	SAY DESC @51408

COPY ~Spells/data/spells/revised_spells/goodberry/sppr207.spl~ ~override~ // 'BRUTE' method
        SAY UNIDENTIFIED_DESC @51407
	SAY DESC @51407

//Spell Revisions: Just copy over an unselectable version of goodberry
ACTION_IF FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN   //any version of sr
  COPY ~Spells/data/spells/revised_spells/goodberry/spell_rev/sppr118.spl~ ~override~ //
END


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Charm Person_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Entropy Shield_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//IWD version only (my version already does this).  Protects vs. sol's searing orb (et al if necessary)

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_________________________________________________________________Charm person or mammal --> Charm Beast_______________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//

/*opcode = 177
target = 2
power = 0
timing = 4
parameter1 = 5
parameter2 = 160
power = 0
resist_dispel = 2
duration = 1
probability1 = 100
probability2 = 0
dicenumber = 0
dicesize = 0
savingthrow = 0
savebonus = 0
header =
insert_point = 7
resource = POOL1a10   */

/*

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////DESTRUCTION///////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//Smite_____________________________________________________________________________
ADD_SPELL ~Spells/spheres/spells/Destruction/b_pr101.spl~ 1 1 ~CLERIC_SMITE~
	SAY NAME1 @50401
	SAY NAME2 @50401
	SAY UNIDENTIFIED_DESC @50402
	SAY DESC @50402
COPY ~Spells/spheres/spells/Destruction/b_pr101.eff~ ~override~     //
COPY ~Spells/spheres/spells/Destruction/SPUNHOLY.bam~ ~override~     //
COPY ~Spells/spheres/spells/Destruction/EFF_E01.WAV~ ~override~     //

//Shatter__________________________________________________________________________________
//icons
COPY ~Spells/spheres/spells/Destruction/b_c204b.bam~ ~override~  // Shatter
COPY ~Spells/spheres/spells/Destruction/b_c204c.bam~ ~override~  // Shatter
//spell etc
ADD_SPELL ~Spells/spheres/spells/Destruction/b_pr201.spl~ 1 2 ~CLERIC_SHATTER~ //Curse Spell
        SAY NAME1 @50408
        SAY NAME2 @50408
        SAY UNIDENTIFIED_DESC @50409
	SAY DESC @50409
COPY ~Spells/spheres/spells/Destruction/b_pr201A.spl~ ~override~ // Shatter 2nd
COPY ~Spells/spheres/spells/Destruction/b_pr201B.spl~ ~override~ // Shatter   3rd
COPY ~Spells/spheres/spells/Destruction/b_pr201A.eff~ ~override~ // Shatter  x dam golem
COPY ~Spells/spheres/spells/Destruction/b_pr201B.eff~ ~override~ // Shatter  cast 2
COPY ~Spells/spheres/spells/Destruction/b_pr201C.eff~ ~override~ // Shatter  x dam
COPY ~Spells/spheres/spells/Destruction/b_pr201D.eff~ ~override~ // Shatter  cast 3
COPY ~Spells/spheres/spells/Destruction/EFF_E01.WAV~ ~override~     //

//Need to copy all elementals, and change their type to monster
COPY_EXISTING_REGEXP GLOB ~.*\.cre~ ~override~ //copies all cre files
	PATCH_IF (~%SOURCE_SIZE%~ > ~0x71~) BEGIN
		READ_BYTE ~0x272~ ~type~ //reads the byte containing cre type
		PATCH_IF (~%type%~ = ~145~) BEGIN
	          WRITE_SHORT 0x271 255
	          WRITE_BYTE  0x272 145   //I have no idea why I need to do this...
                END
         END
BUT_ONLY_IF_IT_CHANGES

//Shout__________________________________________________________________________________
ADD_PROJECTILE ~Spells/spheres/spells/Destruction/b_sht01.pro~   //projectile
COPY ~Spells/spheres/spells/Destruction/SHOUTT.bam~ ~override~     //
COPY ~Spells/spheres/spells/Destruction/#FF_M101.WAV~ ~override~     //
ADD_SPELL ~Spells/spheres/spells/Destruction/b_pr402.spl~ 1 4 ~CLERIC_SHOUT~ //
        SAY NAME1 @50405
        SAY NAME2 @50405
        SAY UNIDENTIFIED_DESC @50406
	SAY DESC @50406
	WRITE_SHORT 0x098 ~%b_sht01%~  //Projectile

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
//////////////////////// AFFLICTION //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//Waves of Agony__________________________________________________________________________________
ADD_SPELL ~Spells/spheres/spells/affliction/b_Pr501.spl~ 1 5 ~CLERIC_WAVES_OF_AGONY~ //
        SAY NAME1 @51201
        SAY NAME2 @51201
        SAY UNIDENTIFIED_DESC @51202
	SAY DESC @51202
COPY ~Spells/spheres/spells/affliction/b_ILM04a.spl~ ~override~ // Wave of Agony spla
COPY ~Spells/spheres/spells/affliction/b_ILM04b.spl~ ~override~ // etc.
COPY ~Spells/spheres/spells/affliction/b_ILM04.eff~ ~override~ //
  SAY 0x1c @51203 //Wracked in Agony
COPY ~Spells/spheres/spells/affliction/EFF_E05.WAV~ ~override~ //

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
////////////////////////            //////////////////////////
////////////////////////   PLANT    //////////////////////////
////////////////////////            //////////////////////////
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

//Nature's Wrath_________________________________________________________________
ADD_SPELL ~Spells/spheres/spells/plant/b_Pr601.spl~ 1 6 ~CLERIC_NATURES_WRATH~ //
        SAY NAME1 @51401
        SAY NAME2 @51401
        SAY UNIDENTIFIED_DESC @51402
	SAY DESC @51402
 COPY ~Spells/spheres/spells/plant/SHMBLR.ITM~ ~override~ //
 COPY ~Spells/spheres/spells/plant/SISHAPE06.bam~ ~override~ //  
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~CLERIC_NATURES_WRATH~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR resource = EVAL ~%spell_res%~
  END      //
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = EVAL ~B_FO601~ END
 
//CONTINUE HERE

//Assassin Vines_________________________________________________
ACTION_IF GAME_IS ~bgee sod bg2ee eet iwdee~ THEN BEGIN    //Not sure why, but I originally limited this to IWDEE TEST!
 COPY ~Spells/spheres/spells/plant/b_c601.spl~ ~override~ //Assassin Vines
        SAY NAME1 @51404
        SAY NAME2 @51404
        SAY UNIDENTIFIED_DESC @51405
	SAY DESC @51405
 COPY_EXISTING ~d5phpla6.spl~ ~override~
    LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_c601~ END

COPY_EXISTING ~b_c601.spl~ ~override/b_Fo602.spl~ // Assassin Vines-FOCUS
        SAY UNIDENTIFIED_DESC @51406
	SAY DESC @51406
  WRITE_LONG 0x34 5
COPY_EXISTING ~d5ffpla6.spl~ ~override~
         LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_Fo602~ END
BUT_ONLY
END

//Stone Fist__________________________________________________________________________________
//EARTH
//icons
COPY ~Spells/spheres/spells/earth/b_c303b.bam~ ~override~ // Stone Fist
COPY ~Spells/spheres/spells/earth/b_c303c.bam~ ~override~ // Stone Fist
//spell etc
COPY ~Spells/spheres/spells/earth/b_pr301.spl~ ~override~ // Stone Fist
        SAY NAME1 @51501
        SAY NAME2 @51501
        SAY UNIDENTIFIED_DESC @51503
	SAY DESC @51503
COPY ~Spells/spheres/spells/earth/b_pr301.itm~ ~override~ // Actual Fist
        SAY NAME1 @51501
        SAY NAME2 @51501
        SAY UNIDENTIFIED_DESC @51504
	SAY DESC @51504
 COPY_EXISTING ~d5phear3.spl~ ~override~
         LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_pr301~ END
 BUT_ONLY
//END
COPY ~Spells/spheres/spells/earth/b_pr301.spl~ ~override/b_Fo301.spl~ // Stone Fist-FOCUS
        SAY NAME1 @51501
        SAY NAME2 @51501
        SAY UNIDENTIFIED_DESC @51503
	SAY DESC @51503
  WRITE_LONG 0x34 2
COPY_EXISTING ~d5ffear3.spl~ ~override~
         LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_Fo301~ END
BUT_ONLY

//WATER
//Summon Water Elemental______________________________________________________________________
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN    //IWDEE only animation
 COPY ~Spells/spheres/spells/water/b_Pr602.spl~ ~override~ // Summon Water Elemental
        SAY NAME1 @51701
        SAY NAME2 @51701
        SAY UNIDENTIFIED_DESC @51702
	SAY DESC @51702
 COPY ~Spells/spheres/spells/water/B_PRWA1.eff~ ~override~ // Summon Water Elemental
 COPY ~Spells/spheres/spells/water/B_PRWA2.eff~ ~override~ // Summon Water Elemental
 COPY ~Spells/spheres/spells/water/b_wele1.itm~ ~override~ // Summon Water Elemental
 COPY ~Spells/spheres/spells/water/b_gensu.itm~ ~override~ // Summon Water Elemental
 COPY_EXISTING ~cywatere.cre~ ~override/b_wele1.cre~
  WRITE_BYTE 0x270 4  //Ally
  ADD_CRE_ITEM ~b_gensu~ #0 #0 #0 ~IDENTIFIED~ ~amulet~ //Gender to summoned
  ADD_CRE_ITEM ~b_wele1~ #0 #0 #0 ~IDENTIFIED~ ~weapon1~ EQUIP//Adds weapon
 COPY ~Spells/spheres/spells/water/b_wele2.itm~ ~override~ // Summon Water Elemental
 COPY_EXISTING ~cywatere.cre~ ~override/b_wele2.cre~
  WRITE_BYTE 0x270 4  //Ally
  WRITE_BYTE 0x234 16  //Level
  WRITE_BYTE 0x238 22  //Strength
  WRITE_BYTE 0x23c 15  //Dex
  WRITE_BYTE 0x23d 16  //COn
  WRITE_BYTE 0x52 3  //THAC0
  WRITE_BYTE 0x54 3  //death
  WRITE_BYTE 0x55 5  //Wands
  WRITE_BYTE 0x56 4  //Poly
  WRITE_BYTE 0x57 3  //Breath
  WRITE_BYTE 0x58 6  //Spell
  WRITE_SHORT 0x24 168 //
  WRITE_SHORT 0x26 168 // Current and max hp
  ADD_CRE_ITEM ~b_wele2~ #0 #0 #0 ~IDENTIFIED~ ~weapon1~ EQUIP//Adds weapon
  ADD_CRE_ITEM ~b_gensu~ #0 #0 #0 ~IDENTIFIED~ ~amulet~ //Gender to summoned
 COPY_EXISTING ~d5phwat6.spl~ ~override~
    LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_Pr602~ END
 BUT_ONLY
 COPY_EXISTING ~b_Pr602.spl~ ~override/b_Fo602.spl~ // Conjure Water-FOCUS
        SAY UNIDENTIFIED_DESC @51703
	SAY DESC @51703
  WRITE_LONG 0x34 5
 COPY_EXISTING ~d5ffwat6.spl~ ~override~
         LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_Fo602~ END
 BUT_ONLY
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN    //BG2EE only creature
 COPY ~Spells/spheres/spells/water/b_Pr602.spl~ ~override~ // Summon Water Elemental
        SAY NAME1 @51701
        SAY NAME2 @51701
        SAY UNIDENTIFIED_DESC @51702
	SAY DESC @51702
 COPY ~Spells/spheres/spells/water/B_PRWA1.eff~ ~override~ // Summon Water Elemental
 COPY ~Spells/spheres/spells/water/B_PRWA2.eff~ ~override~ // Summon Water Elemental
 COPY ~Spells/spheres/spells/water/b_wele1.itm~ ~override~ // Summon Water Elemental
 COPY ~Spells/spheres/spells/water/b_gensu.itm~ ~override~ // Summon Water Elemental
 COPY_EXISTING ~elwatg01.cre~ ~override/b_wele1.cre~
  WRITE_BYTE 0x270 4  //Ally
  ADD_CRE_ITEM ~b_gensu~ #0 #0 #0 ~IDENTIFIED~ ~amulet~ //Gender to summoned
  ADD_CRE_ITEM ~b_wele1~ #0 #0 #0 ~IDENTIFIED~ ~weapon1~ EQUIP//Adds weapon
 COPY ~Spells/spheres/spells/water/b_wele2.itm~ ~override~ // Summon Water Elemental
 COPY_EXISTING ~elwatg01.cre~ ~override/b_wele2.cre~
  WRITE_BYTE 0x270 4  //Ally
  WRITE_BYTE 0x234 16  //Level
  WRITE_BYTE 0x238 22  //Strength
  WRITE_BYTE 0x23c 15  //Dex
  WRITE_BYTE 0x23d 16  //COn
  WRITE_BYTE 0x52 3  //THAC0
  WRITE_BYTE 0x54 3  //death
  WRITE_BYTE 0x55 5  //Wands
  WRITE_BYTE 0x56 4  //Poly
  WRITE_BYTE 0x57 3  //Breath
  WRITE_BYTE 0x58 6  //Spell
  WRITE_SHORT 0x24 168 //
  WRITE_SHORT 0x26 168 // Current and max hp
  ADD_CRE_ITEM ~b_wele2~ #0 #0 #0 ~IDENTIFIED~ ~weapon1~ EQUIP//Adds weapon
  ADD_CRE_ITEM ~b_gensu~ #0 #0 #0 ~IDENTIFIED~ ~amulet~ //Gender to summoned
 COPY_EXISTING ~d5phwat6.spl~ ~override~
    LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_Pr602~ END
 BUT_ONLY
 COPY_EXISTING ~b_Pr602.spl~ ~override/b_Fo602.spl~ // Conjure Water-FOCUS
  SAY UNIDENTIFIED_DESC @51703
  WRITE_LONG 0x34 5
 COPY_EXISTING ~d5ffwat6.spl~ ~override~
         LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_Fo602~ END
 BUT_ONLY
END

//Ice Blade_________________________________________________________
ACTION_IF GAME_IS ~bgee sod bg2ee eet iwdee~ THEN BEGIN    //Not sure why, but I originally limited these spells to IWDEE TEST!
//Icons
COPY ~Spells/spheres/spells/water/b_c203b.bam~ ~override~   //bam
COPY ~Spells/spheres/spells/water/b_c203c.bam~ ~override~   //bam
//blades
COPY ~Spells/spheres/spells/water/moonbla.bam~ ~override~   //bam
COPY ~Spells/spheres/spells/water/b_iceb1.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51710
	SAY DESC @51710
COPY ~Spells/spheres/spells/water/b_iceb2.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51711
	SAY DESC @51711
COPY ~Spells/spheres/spells/water/b_iceb3.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51712
	SAY DESC @51712
COPY ~Spells/spheres/spells/water/b_iceb4.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51713
	SAY DESC @51713
COPY ~Spells/spheres/spells/water/b_iceb5.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51714
	SAY DESC @51714
COPY ~Spells/spheres/spells/water/b_iceb6.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51715
	SAY DESC @51715
COPY ~Spells/spheres/spells/water/b_iceb7.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51716
	SAY DESC @51716
COPY ~Spells/spheres/spells/water/b_iceb8.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51717
	SAY DESC @51717
COPY ~Spells/spheres/spells/water/b_iceb9.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51718
	SAY DESC @51718
COPY ~Spells/spheres/spells/water/b_iceb10.itm~ ~override~   //blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51719
	SAY DESC @51719
COPY ~Spells/spheres/spells/water/b_c203.spl~ ~override~ // Ice Blade
        SAY NAME1 @51704
        SAY NAME2 @51704
        SAY UNIDENTIFIED_DESC @51705
	SAY DESC @51705
 COPY_EXISTING ~d5phwat2.spl~ ~override~
    LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_c203~ END
 BUT_ONLY
 COPY_EXISTING ~b_c203.spl~ ~override/b_Fo202.spl~ // Ice Blade-FOCUS
  SAY UNIDENTIFIED_DESC @51705
  WRITE_LONG 0x34 1
 COPY_EXISTING ~d5ffwat2.spl~ ~override~
         LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_Fo202~ END
 BUT_ONLY

//Frost Fingers____________________________________________________________
//icons
COPY ~Spells/spheres/spells/water/b_c103b.bam~ ~override~ // Frost Fingers
COPY ~Spells/spheres/spells/water/b_c103c.bam~ ~override~ // Frost Fingers
//spell etc
ADD_PROJECTILE ~Spells/spheres/spells/water/b_c103.pro~
COPY ~Spells/spheres/spells/water/b_c103.spl~ ~override~ // Frost Fingers
        SAY NAME1 @51707
        SAY NAME2 @51707
        SAY UNIDENTIFIED_DESC @51708
	SAY DESC @51708
	WRITE_SHORT 0x098 ~%b_c103%~
 COPY_EXISTING ~d5phwat1.spl~ ~override~
    LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_c103~ END
 BUT_ONLY
 COPY_EXISTING ~b_c103.spl~ ~override/b_Fo101.spl~ // Ice Blade-FOCUS
        SAY UNIDENTIFIED_DESC @51709
	SAY DESC @51709
  WRITE_LONG 0x34 1
 COPY_EXISTING ~d5ffwat1.spl~ ~override~
         LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_Fo101~ END
 BUT_ONLY

END

//__________________________________________________________________________________

//SHADOW

//Cloak of Darkness_________________________________________________________
//icons
COPY ~Spells/spheres/spells/shadow/b_c302b.bam~ ~override~ // Cloak of Darkness
COPY ~Spells/spheres/spells/shadow/b_c302c.bam~ ~override~ // Cloak of Darkness
//spell etc
COPY ~Spells/spheres/spells/shadow/b_c302.spl~ ~override~ // Cloak of Darkness
        SAY NAME1 @52003
        SAY NAME2 @52003
        SAY UNIDENTIFIED_DESC @52004
	SAY DESC @52004
	COPY_EXISTING ~d5phsha3.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_c302~ END // cloak of darkness
	COPY_EXISTING ~b_c302.spl~ ~override/b_fo302.spl~
        SAY UNIDENTIFIED_DESC @52005
	SAY DESC @52005
           WRITE_LONG 0x34 2
	COPY_EXISTING ~d5ffsha3.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_fo302~ END // focus cloak of darkness
	BUT_ONLY

//special case: shadowstep__________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~spsd02.spl~ BEGIN
	COPY ~Spells/spheres/spells/shadow/spsd02.spl~ ~override~ // Shadowstep
        SAY NAME1 @52001
        SAY NAME2 @52001
        SAY UNIDENTIFIED_DESC @52002
	SAY DESC @52002
END
ACTION_IF FILE_EXISTS_IN_GAME ~spsd02.spl~ BEGIN
	COPY_EXISTING ~d5phsha5.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~spsd02~ END // skeleton warrior
	COPY_EXISTING ~spsd02.spl~ ~override/d5fosd02.spl~
        WRITE_LONG 0x34 4
	COPY_EXISTING ~d5ffsha5.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~d5fosd02~ END // skeleton warrior
	BUT_ONLY
END


//__________________________________________________________________________________

//CHARM/THOUGHT
//Forbiddance___________________________________________________________________
ACTION_IF GAME_IS ~bgee sod bg2ee eet iwdee~ THEN BEGIN    //originally made iwdee only test
//icons
COPY ~Spells/spheres/spells/charm/b_c201b.bam~ ~override~ // Forbiddance
COPY ~Spells/spheres/spells/charm/b_c201c.bam~ ~override~ // Forbiddance
//spell etc
COPY ~Spells/spheres/spells/charm/b_c201.spl~ ~override~ // Forbiddance
        SAY NAME1 @50800
        SAY NAME2 @50800
        SAY UNIDENTIFIED_DESC @50801
	SAY DESC @50801
	COPY_EXISTING ~d5phtho2.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_c201~ END // Forbiddance
	COPY_EXISTING ~b_c201.spl~ ~override/b_fo203.spl~
        SAY UNIDENTIFIED_DESC @50802
	SAY DESC @50802
           WRITE_LONG 0x34 1
             LPF ALTER_EFFECT
              INT_VAR match_opcode = 324
              STR_VAR resource = EVAL ~b_fo203~
             END
	COPY_EXISTING ~d5fftho2.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_fo203~ END // focus Forbiddance
	BUT_ONLY

//Murderous Command_____________________________________________________________
//icons
COPY ~Spells/spheres/spells/charm/b_c301b.bam~ ~override~ // Murderous Command
COPY ~Spells/spheres/spells/charm/b_c301c.bam~ ~override~ // Murderous Command
//spell etc
COPY ~Spells/spheres/spells/charm/b_c301.spl~ ~override~ // Murderous Command
        SAY NAME1 @50803
        SAY NAME2 @50803
        SAY UNIDENTIFIED_DESC @50804
	SAY DESC @50804

COPY_EXISTING ~d5phtho3.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_c301~ END // Murderous Command

COPY_EXISTING ~b_c301.spl~ ~override/b_f301.spl~
        SAY UNIDENTIFIED_DESC @50805
	SAY DESC @50805
           WRITE_LONG 0x34 2
             LPF ALTER_EFFECT
              INT_VAR match_opcode = 324
              STR_VAR resource = EVAL ~b_f301~
             END
COPY_EXISTING ~d5fftho3.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_f301~ END // focus Murderous Command
	BUT_ONLY
END
//end ee only
//__________________________________________________________________________________

//DEATH

//Pacify the Dead______________________________________________________________
//icons
COPY ~Spells/spheres/spells/death/b_c202b.bam~ ~override~ // Pacify the Dead
COPY ~Spells/spheres/spells/death/b_c202c.bam~ ~override~ // Pacify the Dead
//spells etc
COPY ~Spells/spheres/spells/death/b_c202.spl~ ~override~ // Pacify the Dead
        SAY NAME1 @50301
        SAY NAME2 @50301
        SAY UNIDENTIFIED_DESC @50302
	SAY DESC @50302
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324
      parameter1 = 0
      parameter2 = 2
      STR_VAR resource = EVAL ~b_c202~
     END
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_c202~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_f201~ END
COPY_EXISTING ~d5phdea2.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_c202~ END // Murderous Command
COPY_EXISTING ~b_c202.spl~ ~override/b_f201.spl~
        SAY UNIDENTIFIED_DESC @50303
	SAY DESC @50303
           WRITE_LONG 0x34 1
COPY_EXISTING ~d5ffdea2.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_f201~ END // Murderous Command
//add removal
ACTION_IF FILE_EXISTS_IN_GAME ~.spl~ BEGIN
 COPY_EXISTING ~spwi312.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_c202~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_f201~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~.spl~ BEGIN
 COPY_EXISTING ~spwish25.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_c202~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_f201~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~.spl~ BEGIN
 COPY_EXISTING ~spin146.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_c202~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_f201~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~.spl~ BEGIN
 COPY_EXISTING ~spin977.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_c202~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_f201~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~.spl~ BEGIN
 COPY_EXISTING ~spwm164.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_c202~ END
  LPF CLONE_EFFECT INT_VAR match_opcode = 40 opcode = 321 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = EVAL ~b_f201~ END
END

  //Eyes of the Dead_________________________________________________________
//Icons
COPY ~Spells/spheres/spells/death/b_c104b.bam~ ~override~ //
COPY ~Spells/spheres/spells/death/b_c104c.bam~ ~override~ //
//spell etc
COPY ~Spells/spheres/spells/death/b_c104.spl~ ~override~ //
        SAY NAME1 @50304
        SAY NAME2 @50304
        SAY UNIDENTIFIED_DESC @50305
	SAY DESC @50305
COPY_EXISTING ~d5phdea1.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_c104~ END // Eyes of the Dead
COPY_EXISTING ~b_c104.spl~ ~override/b_f102.spl~
        SAY UNIDENTIFIED_DESC @50306
	SAY DESC @50306
           WRITE_LONG 0x34 1
                LPF ALTER_EFFECT
                  INT_VAR match_opcode = 324
                  STR_VAR resource = EVAL ~b_f102~
                END
COPY_EXISTING ~d5ffdea1.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_f102~ END //
		
//Dusrupt Undead_________________________________________________________
//Icons
COPY ~Spells/spheres/spells/death/b_c105b.bam~ ~override~ //
COPY ~Spells/spheres/spells/death/b_c105c.bam~ ~override~ //
//spell etc
COPY ~Spells/spheres/spells/death/b_c105.spl~ ~override~ //
        SAY NAME1 @50307
        SAY NAME2 @50307
        SAY UNIDENTIFIED_DESC @50308
	SAY DESC @50308
COPY_EXISTING ~d5phdea1.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_c105~ END // Eyes of the Dead
COPY_EXISTING ~b_c105.spl~ ~override/b_f103.spl~
        SAY UNIDENTIFIED_DESC @50309
	SAY DESC @50309
           WRITE_LONG 0x34 1
                LPF ALTER_EFFECT
                  INT_VAR match_opcode = 324
                  STR_VAR resource = EVAL ~b_f103~
                END
COPY_EXISTING ~d5ffdea1.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_f103~ END //
//__________________________________________________________________________________

//ANIMAL


//Animal Eyes____________________________________________________________
//icons
COPY ~Spells/spheres/spells/animal/b_c102b.bam~ ~override~ // Animal eyes
COPY ~Spells/spheres/spells/animal/b_c102c.bam~ ~override~ // Animal eyes
//spell etc
COPY ~Spells/spheres/spells/animal/b_c102.spl~ ~override~ // Animal eyes
        SAY NAME1 @51101
        SAY NAME2 @51101
        SAY UNIDENTIFIED_DESC @51102
	SAY DESC @51102
COPY_EXISTING ~d5phani1.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_c102~ END //
COPY_EXISTING ~b_c102.spl~ ~override/b_f101.spl~
        SAY UNIDENTIFIED_DESC @51103
	SAY DESC @51103
           WRITE_LONG 0x34 1
                LPF ALTER_EFFECT
                  INT_VAR match_opcode = 324
                  STR_VAR resource = EVAL ~b_f101~
                END

COPY_EXISTING ~d5ffani1.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_f101~ END //
//__________________________________________________________________________________
//DREAD

//Misfire____________________________________________________________________
//icons
COPY ~Spells/spheres/spells/dread/b_c501b.bam~ ~override~ // Misfire
COPY ~Spells/spheres/spells/dread/b_c501c.bam~ ~override~ // Misfire
//spl etc
COPY ~Spells/spheres/spells/dread/b_c501.eff~ ~override~ // Misfire
  SAY 0x1c @50901     //Misfire

COPY ~Spells/spheres/spells/dread/b_c501.spl~ ~override~ // Misfire
        SAY NAME1 @50901
        SAY NAME2 @50901
        SAY UNIDENTIFIED_DESC @50902
	SAY DESC @50902
COPY_EXISTING ~d5phdre5.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_c501~ END //
COPY_EXISTING ~b_c501.spl~ ~override/b_f501.spl~
        SAY UNIDENTIFIED_DESC @50903
	SAY DESC @50903
           WRITE_LONG 0x34 4
                LPF ALTER_EFFECT
                  INT_VAR match_opcode = 321
                  STR_VAR resource = EVAL ~b_f501~
                END
COPY_EXISTING ~d5ffdre5.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_f501~ END //


//AIR

//Storm Wall_________________________________________________________________
COPY ~Spells/spheres/spells/air/b_elect1.bam~ ~override~ // 
COPY ~Spells/spheres/spells/air/b_storm1.vvc~ ~override~ //
COPY ~Spells/spheres/spells/air/b_c401a.spl~ ~override~ //sub-spell
ADD_PROJECTILE ~Spells/spheres/spells/air/b_storm1.pro~   //pro
COPY ~Spells/spheres/spells/air/b_c401.spl~ ~override~ //spell
        SAY NAME1 @51601
        SAY NAME2 @51601
        SAY UNIDENTIFIED_DESC @51602
	SAY DESC @51602
	WRITE_SHORT 0x098 ~%b_storm1%~
COPY_EXISTING ~d5phair4.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_c401~ END //
COPY_EXISTING ~b_c401.spl~ ~override/b_f401.spl~
        SAY UNIDENTIFIED_DESC @51603
	SAY DESC @51603
           WRITE_LONG 0x34 3
                LPF ALTER_EFFECT
                  INT_VAR match_opcode = 206
                  STR_VAR resource = EVAL ~b_f401~
                END
COPY_EXISTING ~d5ffair4.spl~ ~override~
		LPF CLONE_EFFECT INT_VAR match_opcode=171 STR_VAR match_resource=~SPWI101~ resource = ~b_f401~ END //

     */