//special thanks to Subtledoctor and Aquadrizzt for this code

ACTION_DEFINE_ASSOCIATIVE_ARRAY prot BEGIN

~%spell_res%~ => bless
b_po020 => bless  //canticle main spell (need to address extra ability which shoucl conditionally be removed and canticle readded...)
b_po030 => bless  //maladiction (Special)

END

// This code is copied from Mike1072's armor_list.tpa file. 
// WeiDU is now on my hate list as well - Yaro, 7/26
