//Priest Orisons b_po###  (010, 020,...990) 010 = @@101000000; 020 = @@102000000...990 = @199000000


//At least two options regarding relatively 'useless' spells.  
//Infravision, Hold ANimal, Magic Stone, Goodberry Converted to cantrips, or only converted to cantrips if B_REVISE Is installed (sometimes if SR installed)...

////////////////////////////////////////////////////////////////
/////////////////   Cantrips and Orisons    ////////////////////
////////////////////////////////////////////////////////////////

//NOTE: Add compatibility with sphere system
//compatibility: Entropy shield, if present, should protect vs all, or almost all, cantrip projectiles.  
////CHECK Malediction et alIWDEE   (WILL NEED TO COME BACK TO THIS ONCE SR CAN BE INSTALLED ON IWDEE...

// SD: eliminate #bonecir.spl from IWDEE
ACTION_IF GAME_IS ~iwdee~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME "#bonecir.spl" BEGIN
	DISABLE_FROM_KEY "#bonecir.spl"
  END
  ACTION_IF FILE_EXISTS "override\#bonecir.spl" BEGIN
	DELETE "override\#bonecir.spl"
  END
END

//template
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________________Template__________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE: no
//                                          IWDification: no
//                                          My IWD spells: no
//                                          my revised spells: no
//                                          spheres: no
//                                          SR: no
//                                          Other: no

////////////////////////////
//////NOTES:
////////////////////////////

///////////////////////////////////////////////
//////Spell Basics: Pros, effs, bams, wavs, etc
///////////////////////////////////////////////

///////////////////////////////////////////////////
//////Spell Itself (and spell biz (e.g. sec spells)
///////////////////////////////////////////////////

////////////////////////////////
//////Add Icons and Projectiles:
////////////////////////////////

////////////////////////////
//////Portrait Icons:
////////////////////////////

////////////////////////////
//////Immunity/Prot Lists:
////////////////////////////

////////////////////////////
//////Compatibility
////////////////////////////



////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////                                  /////////////////////////////
/////////////////////////////               Mage               /////////////////////////////
/////////////////////////////              Cantrips            /////////////////////////////
/////////////////////////////                                  /////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//__________________________________________________________________Acid Splash_________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR: Yes
//                                          Other: no need as far as I can tell
//
//this cantrip virtually assumes SR shocking grasp.
//Projectile
//ADD_PROJECTILE ~%mod_folder%/data/cantrips/arcane/b_1c101.pro~   //projectile
//VVC
//bam
//COPY ~%mod_folder%/data/cantrips/arcane/b_frost1.bam~ ~override~   //animation
//animations
//3d animation
//sounds  Check for TRA_17.wav
//COPY ~%mod_folder%/data/cantrips/arcane/#EFF_P99.WAV~ ~override~   //sound
//effs
//Spell itself
COPY ~%mod_folder%/data/cantrips/arcane/b_wc102.spl~  ~override~
        SAY NAME1 @200006001
        SAY NAME2 @200006001
        SAY UNIDENTIFIED_DESC @200006002
	SAY DESC @200006002
  LPF MAKE_CANTRIP END      //Default make_cantrip



//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//___________________________________________________________________Audible Glamer_____________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR: Yes
//                                          Other: no need as far as I can tell
//
//this cantrip virtually assumes SR shocking grasp.
//Projectile
//ADD_PROJECTILE ~%mod_folder%/data/cantrips/arcane/b_1c101.pro~   //projectile
//VVC
//bam
//COPY ~%mod_folder%/data/cantrips/arcane/b_frost1.bam~ ~override~   //animation
//animations
//3d animation
//sounds  Check for TRA_17.wav
COPY ~%mod_folder%/data/cantrips/arcane/b_wisp1.WAV~ ~override~   //sound
COPY ~%mod_folder%/data/cantrips/arcane/b_wisp2.WAV~ ~override~   //sound
COPY ~%mod_folder%/data/cantrips/arcane/b_wisp3.WAV~ ~override~   //sound
COPY ~%mod_folder%/data/cantrips/arcane/b_wisp4.WAV~ ~override~   //sound
COPY ~%mod_folder%/data/cantrips/arcane/b_wisp5.WAV~ ~override~   //sound
COPY ~%mod_folder%/data/cantrips/arcane/b_wisp6.WAV~ ~override~   //sound
COPY ~%mod_folder%/data/cantrips/arcane/b_wisp7.WAV~ ~override~   //sound
//effs
//Spell itself
COPY ~%mod_folder%/data/cantrips/arcane/B_WC103.spl~  ~override~
        SAY NAME1 @200009001
        SAY NAME2 @200009001
        SAY UNIDENTIFIED_DESC @200009002
	SAY DESC @200009002
  LPF MAKE_CANTRIP STR_VAR spell_name = ~B_WC103~ END      //Default make_cantrip


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Chill Touch____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR:
//                                          Other: no need as far as I can tell
//

//All versions of Chill Touch are converted to a cantrip, even if SR is installed
 COPY_EXISTING ~SPWI117.spl~ ~override/b_wc005.spl~      //Copy spell as innate
  LPF MAKE_CANTRIP STR_VAR spell_name = ~B_WC005~ END      //Default make_cantrip

COPY_EXISTING ~b_wc005.spl~ ~override~
 SPRINT old @200002003//old text
 SPRINT new @200002004//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //Level: Cantrip
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //

 COPY_EXISTING ~SPWI117.spl~ ~override~   //Copy over the original spell
    WRITE_LONG 0x1e ~0x7fc0~ //  wildmage spell but...
    WRITE_BYTE 0x21 (THIS | 0b10000000) //exlcude wildmage

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Drench_________________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR:
//
//                                          Other:
//Adding the cantrip either way

//Animation
COPY ~%mod_folder%/data/cantrips/arcane/b_wet.bam~ ~override~
//spell itself
COPY ~%mod_folder%/data/cantrips/arcane/b_wc003.spl~ ~override~   //Drench
        SAY NAME1 @200005001
        SAY NAME2 @200005001
        SAY UNIDENTIFIED_DESC @200005002
	SAY DESC @200005002
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 324             //
      STR_VAR resource = EVAL ~b_wc003~
  END
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 318             //
      STR_VAR resource = EVAL ~b_wc003~
  END
 SET strref = RESOLVE_STR_REF(@200005003)
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 139 parameter1 = %strref%   END      //
  LPF ALTER_SPELL_TYPE
   INT_VAR   spell_type = 4  location = 2 failure = 0
  END      //

//CONTINUE

/* 
//When Shround of flame is added to non-IWDEE games...
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_SHROUD_OF_FLAME~
  RET spell_res
END
COPY_EXISTING ~b_wc003.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR match_opcode = 321            //
      STR_VAR match_resource = ~SPWI524~ resource = EVAL ~%spell_res%~
  END
*/
//Create Dispel fire effect batch macro

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Drowse_________________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR:
//                                          Other:
//
//Projectile
//ADD_PROJECTILE ~%mod_folder%/data/cantrips/arcane/b_1c101.pro~   //projectile
//VVC
//bam
//COPY ~%mod_folder%/data/cantrips/arcane/b_frost1.bam~ ~override~   //animation
//animations
//3d animation
//sounds  Check for TRA_17.wav
//COPY ~%mod_folder%/data/cantrips/arcane/#EFF_P99.WAV~ ~override~   //sound
//effs
//Spell itself
COPY ~%mod_folder%/data/cantrips/arcane/b_wc004.spl~  ~override~
        SAY NAME1 @200003001
        SAY NAME2 @200003001
        SAY UNIDENTIFIED_DESC @200003002
	SAY DESC @200003002
//to add: Opponent becomes immune for 1 day.

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//____________________________________________________________Expeditious Retreat_______________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE: no
//                                          IWDification: no
//                                          My IWD spells: no
//                                          my revised spells: no
//                                          spheres: no
//                                          SR: Yes
//                                          Other: no

 ACTION_IF FILE_EXISTS_IN_GAME ~b_cant.itm~ BEGIN   //This spell is a cantrip if cantrips installed
  ACTION_IF NOT FILE_EXISTS_IN_GAME ~dvimhere.mrk~ BEGIN   //any version of sr (not sure about details if SR installed--for now, not if SR installed)
   ACTION_IF (!FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_EXPEDITIOUS_RETREAT~)) BEGIN  //if not IWDEE priest spells..from any source
   COPY ~%mod_folder%/data/iwd_spells/wizard_1/b_w101.spl~ ~override~   //spell itself
        SAY NAME1 @1260000
        SAY NAME2 @1260000
        SAY UNIDENTIFIED_DESC @1260001
	SAY DESC @1260001
  LPF ALTER_EFFECT
      INT_VAR duration = 6
  END      //
  LPF MAKE_CANTRIP STR_VAR spell_name = ~B_W101~ END      //Default make_cantrip


COPY_EXISTING ~B_W101.spl~ ~override~
 SPRINT old @200002003//old text
 SPRINT new @200002004//new text
 SPRINT old1 @200002005//old text
 SPRINT new1 @200002006//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old%~ ~%new%~        //replacing old with new (level to cantrip)
	REPLACE_TEXTUALLY ~%old1%~ ~%new1%~        //replacing old with new (3 rounds to 1)
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //
  END //End not Wiz Exp Retreat
 END //END NOT SR
END //END cantrip version

ACTION_IF (FILE_CONTAINS_EVALUATED(~spell.ids~ ~WIZARD_EXPEDITIOUS_RETREAT~)) BEGIN  //
LAF RES_NUM_OF_SPELL_NAME
  STR_VAR spell_name = ~WIZARD_EXPEDITIOUS_RETREAT~
  RET spell_res
END
COPY_EXISTING ~%spell_res%.spl~ ~override~
  LPF ALTER_EFFECT
      INT_VAR duration = 6
  END      //
  LPF MAKE_CANTRIP STR_VAR spell_name = EVAL  ~%spell_res%~ END      //Default make_cantrip

COPY_EXISTING ~%spell_res%~ ~override~
 SPRINT old1 @200002005//old text
 SPRINT new1 @200002006//new text
  READ_LONG 0x50 "valid"
  PATCH_IF (%valid% >= 0) BEGIN // verify desc is valid
  READ_STRREF 0x50 ~desc~
	INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
	REPLACE_TEXTUALLY ~%old1%~ ~%new1%~        //replacing old with new (3 rounds to 1 round)
	END
  SAY_EVALUATED 0x50 ~%new_desc%~
  END  //
END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//______________________________________________________________Fire Bolt_______________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Credit for this spell goes to SubtleDoctor. Used and modified with permission.

//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR: Yes
//                                          Other: no need as far as I can tell
//
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/cantrips/arcane/D5_MSORN.pro~   //projectile
//VVC
//bam
COPY ~%mod_folder%/data/cantrips/arcane/SPMAGM04.bam~ ~override~   //animation
//animations
//3d animation
//sounds  Check for TRA_17.wav
//COPY ~%mod_folder%/data/cantrips/arcane/#EFF_P99.WAV~ ~override~   //sound
//effs
//Spell itself
COPY ~%mod_folder%/data/cantrips/arcane/d5_wfir.spl~  ~override~
        SAY NAME1 @200007001
        SAY NAME2 @200007001
        SAY UNIDENTIFIED_DESC @200007002
	SAY DESC @200007002
//add projectile
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %D5_MSORN% STR_VAR END


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_______________________________________________________________Frost Ray______________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR:
//                                          Other: no need as far as I can tell
//
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/cantrips/arcane/b_1c101.pro~   //projectile
//VVC
//bam
COPY ~%mod_folder%/data/cantrips/arcane/b_frost1.bam~ ~override~   //animation
//animations
//3d animation
//sounds  Check for TRA_17.wav
//COPY ~%mod_folder%/data/cantrips/arcane/#EFF_P99.WAV~ ~override~   //sound
//effs
//Spell itself
COPY ~%mod_folder%/data/cantrips/arcane/b_wc001.spl~  ~override~
        SAY NAME1 @200001001
        SAY NAME2 @200001001
        SAY UNIDENTIFIED_DESC @200001002
	SAY DESC @200001002
LPF ALTER_SPELL_HEADER INT_VAR projectile = %b_1c101% END

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_____________________________________________________________________Jolt_____________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR: Yes
//                                          Other: no need as far as I can tell
//
//this cantrip virtually assumes SR shocking grasp.
//Projectile
//ADD_PROJECTILE ~%mod_folder%/data/cantrips/arcane/b_1c101.pro~   //projectile
//VVC
//bam
//COPY ~%mod_folder%/data/cantrips/arcane/b_frost1.bam~ ~override~   //animation
//animations
//3d animation
//sounds  Check for TRA_17.wav
//COPY ~%mod_folder%/data/cantrips/arcane/#EFF_P99.WAV~ ~override~   //sound
//effs
//Spell itself
COPY ~%mod_folder%/data/cantrips/arcane/b_wc002.spl~  ~override~
        SAY NAME1 @200002001
        SAY NAME2 @200002001
        SAY UNIDENTIFIED_DESC @200002002
	SAY DESC @200002002

//Need an electricty batch protection.  Immunity to electricity should prot vs. the speed penalty as well (so, prot vs. the cantrip).


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//_____________________________________________________________Magic Bolt_______________________________________________________________________________//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Credit for this spell goes to SubtleDoctor. Used and modified with permission.

//Template               Added:no           Compatiblity:                                         Double Checked: no
//                                          IWDEE:
//                                          IWDification:
//                                          My IWD spells:
//                                          my revised spells:
//                                          spheres:
//                                          SR: Yes
//                                          Other: no need as far as I can tell
//
//Projectile
ADD_PROJECTILE ~%mod_folder%/data/cantrips/arcane/D5_MSBLU.pro~   //projectile
//VVC
//bam
COPY ~%mod_folder%/data/cantrips/arcane/SPMAGM07.bam~ ~override~   //animation
//animations
//3d animation
//sounds  Check for TRA_17.wav
//COPY ~%mod_folder%/data/cantrips/arcane/#EFF_P99.WAV~ ~override~   //sound
//effs
//Spell itself
COPY ~%mod_folder%/data/cantrips/arcane/D5_WIIN.spl~  ~override~
        SAY NAME1 @200008001
        SAY NAME2 @200008001
        SAY UNIDENTIFIED_DESC @200008002
	SAY DESC @200008002
//add projectile
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %D5_MSBLU% STR_VAR END




//CONTINUE FROM HERE
/*
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msred.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msblu.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msgrn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msbrn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msorn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_mswhi.pro~
COPY ~TomeAndBlood/data/cantrips/spmagm02.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm03.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm04.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm05.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm06.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm07.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_cant.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp420.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp710.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp809.bam~ ~override~

COPY ~TomeAndBlood/data/cantrips/d5_wiin.spl~ ~override~
	SAY NAME1 @6025
	SAY UNIDENTIFIED_DESC @6026
	WRITE_SHORT 0x098 ~%d5_msred%~


Cantrips/Orisons: In progress
Minor spells used 'at will'.  Divine cantrips are called Orisons.  
The first number denotes generalist and wild mages (and clerics/druids/mystics), while the second denotes Specialists (and, perhaps, acolytes in FnP):
Level		Cantrips Known	Prepared Cantrips
1		     4/2+1		   2/2+1
2-3		     4/2+1		   3/3+1
4		     6/3+1		   4/4+1
5-12		     7/4+1		   5/5+1
13-20		     9/5+1		   6/6+1
20+		     10/6+1		   7/7+1
Sorcerers/Shaman:
Level			Cantrips Known	
1			       1
2-3			       2
4			       3
5-12			       4
13-20			       5
20+			       6
*/
//Light?  Possible?  Useful?

//Audible Glamer: Target saves or is distracted (deaf immune)

//Catapult: throws dagger

//Air Bubble +4 save vs. gas

//Ceremony:  A dialog cantrip that allows the priest to do a number of things.  All cost gold, or something...
//Ceremony: Bless Water          To add    Implementation: Dialog: costs gold, creates a vial of water that damages undead
//
//Ceremony: Consecrate ground    To add    All enemies in area recieve a -1 penalty to saves.  Cannot be used while enemies present (good for sleeping)
//
//Ceremony: communion            To add    Gives allies a blessing of some sort
//
//Alternatively: Rituals: Cast spells with a gold cost that is more powerful/long lasting than normal (or both?)


//Acid Splash (Conjuration): Casting time 3, sv. Breath +2 or 1d3 points of acid, +1d3 points of acid 1 round later)

//Anticipation (Divination): +2 to AC/breath saves for 1 min

//Bedazzle (Illusion): - 1 to THAC0/AC 2 rounds.  Save or -3 and opponent is blind for 3 seconds.  Opponent becomes immune for 1 day.

//Conjure Critter (Conjuration): Summon minor rodent for 1 turn or so

//Elemental Protection (Abjuration): 5% resist acid/elect/fire/cold for 1 min.

//Earthen Grasp (Transmutation): Earth 'grabs' one opponent.  Save or can't move.  (Need bam!)

//Find Familiar (Conjuration): As the (modified) spell

//Fire Bolt (Evocation): Casting time 3, 1d8 fire damage.  Save vs. breath to avoid.

//Frost Ray (Evocation): Casting time 3, 1d6 cold damage (ray).  Save vs. breath to avoid.

//Magic Bolt (Evocation): Casting time 5, 1d4 magic damage.

//Stiffen Bones (Necromancy): Casting time 1, -1 to THAC0/AC for 2 rounds.  Save vs. death or slowed for that time.


//Sense Magic                    To add    just the reveal magic opcode

//Expedious retreat              To add    1st lev iwdee spell

//Animal Companion (druid)      To add     animal versions of familiar like spell

//Detect Creature               To add     As track

//Disorient                     To add     Creature hesitates for a moment


/*    COde for adding to priest clabs.  Adds 'cure minor wounds' to all priest spells.
Will need to set up an array for cleric vs paladin vs. ranger vs. druid cantrips, and then a different one for fnp spheres dependin on sphere membership
These will need to be added to compatibility code.  
*/

/*
COPY_EXISTING ~CLABPR01.2da~ ~override~ //Base cleric
              ~CLABPA01.2da~ ~override~ //Base paladin
              ~CLABDR01.2da~ ~override~ //Base Druid
              ~CLABRN01.2da~ ~override~ //Base Ranger
              APPEND_FILE ~%mod_folder%/data/cantrips/cleric_cantrips.txt~

//add to clab
//thanks subtledoctor!
COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS ~9~ "rows"
	FOR ( index = 2 ; index < rows ; index = index + 1 ) BEGIN
		READ_2DA_ENTRY %index% 5 9 modclab
		READ_2DA_ENTRY %index% 8 9 modclass
		DEFINE_ASSOCIATIVE_ARRAY d5_base_spell_array BEGIN "%modclab%" => "%modclass%" END
	END
BUT_ONLY


ACTION_PHP_EACH d5_base_spell_array AS bo => zo BEGIN
	ACTION_IF (%zo% = 2) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~%mod_folder%/data/cantrips/cleric_cantrips.txt~
	END
	ACTION_IF (%zo% = 3) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~%mod_folder%/data/cantrips/cleric_cantrips.txt~
	END
	ACTION_IF (%zo% = 6) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~%mod_folder%/data/cantrips/cleric_cantrips.txt~
	END
	ACTION_IF (%zo% = 11) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~%mod_folder%/data/cantrips/cleric_cantrips.txt~
	END
	ACTION_IF (%zo% = 12) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~%mod_folder%/data/cantrips/cleric_cantrips.txt~
	END
	ACTION_IF (%zo% = 21) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~%mod_folder%/data/cantrips/cleric_cantrips.txt~
	END
END
*/

//CONTINUE FROM HERE Create arrays based on fnp, tnb, and vanilla (for both addition and immunities)

//cleric innates
COPY ~%mod_folder%/data/cantrips/divine/b_prc01.spl~ ~override/b_pr01.spl~ //will need to add all cantrips to this and





/* TO BE ADDED


*/

//CONTINUE FROM HERE
/*





COPY ~clchng/Arcane/Cantrip/Spells/b_wc101.spl~ ~override~
  SAY NAME1 @105000 // Fire Bolt
  SAY UNIDENTIFIED_DESC @105001

COPY ~clchng/Arcane/Cantrip/Spells/b_wc102.spl~ ~override~
  SAY NAME1 @105002 //Acid Splash (Cantrip)
  SAY UNIDENTIFIED_DESC @105003
  
COPY ~clchng/Arcane/Cantrip/Spells/b_wc103.spl~ ~override~
  SAY NAME1 @105004 //Cold Ray (Cantrip)
  SAY UNIDENTIFIED_DESC @105005
  
COPY ~clchng/Arcane/Cantrip/Spells/b_wc104.spl~ ~override~
  SAY NAME1 @105006 //Shocking Grasp (Cantrip)
  SAY UNIDENTIFIED_DESC @105007

COPY ~clchng/Arcane/Cantrip/Itm/sgrasp.itm~ ~override~

COPY ~clchng/Arcane/Cantrip/Spells/b_wc105.spl~ ~override~
  SAY NAME1 @105008//Infravision (Cantrip)
  SAY UNIDENTIFIED_DESC @105009
  
COPY ~clchng/Arcane/Cantrip/Spells/b_wc106.spl~ ~override~
  SAY NAME1 @105010//Friends (Cantrip)
  SAY UNIDENTIFIED_DESC @105011

COPY ~clchng/Arcane/Cantrip/Spells/b_wc107.spl~ ~override~
  SAY NAME1 @105012//Chill Touch (Cantrip)
  SAY UNIDENTIFIED_DESC @105013

@105000 = ~Fire Bolt (Cantrip)~
@105001 = ~Fire Bolt (Cantrip)
Level: Cantrip
School: Evocation
Range: Long
Duration: Instant
Casting Time: 3
Area of Effect: 1 creature
Saving Throw: Breath +2

When this cantrip is cast, the caster shoots a bolt of fire from his hand at the target of his choosing causing 1d6 points of fire damage on a sucessful hit.  A creature may make a save vs breath +2 to avoid being damaged by this spell~

@105002 = ~Acid Splash (Cantrip)~
@105003 = ~Acid Splash (Cantrip)
Level: Cantrip
School: Conjuration
Range: Long
Duration: 1 round
Casting Time: 3
Area of Effect: 1 creature
Saving Throw: Breath +2

When this cantrip is cast, the caster conjurs a ball of acid and hurls it towards his target causing 1d3 acid damage on a successful hit on the first round, and an additional 1d3 points of damage one round later.  A creature may make a save vs breath +2 to avoid being damaged by this spell~

@105004 = ~Frost Ray (Cantrip)~
@105005 = ~Frost Ray (Cantrip)
Level: Cantrip
School: Evocation
Range: Long
Duration: Instant
Casting Time: 3
Area of Effect: 1 creature
Saving Throw: Breath +2

When this cantrip is cast, the caster shoots a fay of frost from his hand at the target of his choosing causing 1d6 points of cold damage on a sucessful hit.  A creature may make a save vs breath +2 to avoid being damaged by this spell~


@105006 = ~Shocking Grasp (Cantrip)~
@105007 = ~Shocking Grasp (Cantrip)
Level: Cantrip
School: Alteration
Range: Touch
Duration: 1 round (special)
Casting Time: 1
Area of Effect: 1 creature
Saving Throw: None

When the wizard touches a creature while this cantrip is in effect, an electrical charge will deal 1d8 points of damage to the creature touched. In addition, the grasp itself does 1d2 fist damage (Strength bonuses apply). The wizard only has one charge, and once an opponent has been touched, the spell's energies have been used. If the wizard misses, the spell is wasted.~

@105008 = ~Infravision (Cantrip)~
@105009 = ~Infravision (Cantrip)
Level: Cantrip
School: General
Range: 30 ft.
Duration: 2 hours
Casting Time: 1
Area of Effect: 1 creature
Saving Throw: None

Upon the casting of this spell the recipient gains the ability to see with infravision, just as an elf or a dwarf would. This effect lasts for the duration of the spell or until dispelled.~

@105010 = ~Friends (Cantrip)~
@105011 = ~Friends (Cantrip)
Level: Cantrip
School: Enchantment
Range: 0
Duration: 10 rounds
Casting Time: 1
Area of Effect: The caster
Saving Throw: None

A Friends spell causes the wizard to temporarily gain 6 points of Charisma. Those who view the caster tend to be very impressed with <PRO_HIMHER> and make an effort to be <PRO_HISHER> friends and help <PRO_HIMHER>, as appropriate to the situation. Officious bureaucrats might decide to become helpful; surly gate guards might wax informative; attacking orcs might spare the caster's life, taking <PRO_HIMHER> captive instead.~

@105012 = ~Chill Touch (Cantrip)~
@105013 = ~Chill Touch (Cantrip)
Level: Cantrip
School: Necromancy
Range: 0
Duration: 1 round
Casting Time: 1
Area of Effect: The creature
Saving Throw: Neg.

When the caster completes this spell, a blue glow encompasses <PRO_HISHER> hand. This energy attacks the life force of any living creature upon which the wizard makes a successful melee attack. (Nonliving creatures such as golems and undead are unaffected by this spell.) The creature is punched for 1d2 fist damage (Strength bonuses apply) and must make a Saving Throw vs. Spell or suffer 1d8 points of damage and receive a -2 THAC0 penalty for 5 rounds.~


//////////////////////////////////////
////////// SPl, cre,baf,dlg //////////
//////////////////////////////////////

COPY ~clchng/Arcane/Cantrip/Spl/b_csel1.spl~ ~override~
  SAY NAME1 @115259//Prep Cantrip
@115259 = ~Select your cantrips~
//Clearly not all of this is needed...

COPY ~clchng/Arcane/Cantrip/Spl/b_can00.2da~ ~override~

COMPILE ~clchng/Arcane/Cantrip/Baf/b_csel1.baf~ 
COMPILE ~clchng/Arcane/Cantrip/dlg/b_csel1.d~ 

COPY ~clchng/Arcane/Cantrip/cre/b_csel1.cre~ ~override~
//end to be added
COPY ~TomeAndBlood/data/cantrips/d5_wfir.spl~ ~override~
	SAY NAME1 @6031
	SAY UNIDENTIFIED_DESC @6032
	WRITE_SHORT 0x098 ~%d5_msorn%~

ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msred.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msblu.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msgrn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msbrn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_msorn.pro~
ADD_PROJECTILE ~TomeAndBlood/data/cantrips/d5_mswhi.pro~
COPY ~TomeAndBlood/data/cantrips/spmagm02.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm03.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm04.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm05.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm06.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/spmagm07.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_cant.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp420.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp710.bam~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_sp809.bam~ ~override~
//COPY ~TomeAndBlood/data/cantrips/d5_wildm.2da~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_cstbo.spl~ ~override~
COPY ~TomeAndBlood/data/cantrips/d5_cstpn.spl~ ~override~
//Choose a cantrip
COPY ~TomeAndBlood/data/cantrips/d5_cantr.spl~ ~override~
	SAY NAME1 @6012
COPY ~TomeAndBlood/data/cantrips/d5_cant.spl~ ~override~
	SAY NAME1 @6012
	SAY UNIDENTIFIED_DESC @6013
COPY ~TomeAndBlood/data/cantrips/d5_cant1.spl~ ~override~
	SAY NAME1 @6012
	SAY UNIDENTIFIED_DESC @6013
COPY ~TomeAndBlood/data/cantrips/d5_cant2.spl~ ~override~
	SAY NAME1 @6012
	SAY UNIDENTIFIED_DESC @6013
COPY ~TomeAndBlood/data/cantrips/d5_cant3.spl~ ~override~
	SAY NAME1 @6012
	SAY UNIDENTIFIED_DESC @6013
COPY ~TomeAndBlood/data/cantrips/d5_cantr.2da~ ~override~

//abjurer cantrip: protective shell
COPY ~TomeAndBlood/data/cantrips/d5_maab.spl~ ~override~
	SAY NAME1 @6014
	SAY UNIDENTIFIED_DESC @6015
COPY ~TomeAndBlood/data/cantrips/d5_wiab.spl~ ~override~
	SAY NAME1 @6014
	SAY UNIDENTIFIED_DESC @6015
//conjurer cantrip: summon rabbit	
COPY ~TomeAndBlood/data/cantrips/d5_maco.spl~ ~override~
	SAY NAME1 @6016
	SAY UNIDENTIFIED_DESC @6017
COPY ~TomeAndBlood/data/cantrips/d5_wico.spl~ ~override~
	SAY NAME1 @6016
	SAY UNIDENTIFIED_DESC @6017
COPY ~TomeAndBlood/data/cantrips/d5_rabb.cre~ ~override~
	SAY NAME1 @6018
//diviner cantrip: anticipation
COPY ~TomeAndBlood/data/cantrips/d5_madi.spl~ ~override~
	SAY NAME1 @6019
	SAY UNIDENTIFIED_DESC @6020
COPY ~TomeAndBlood/data/cantrips/d5_widi.spl~ ~override~
	SAY NAME1 @6019
	SAY UNIDENTIFIED_DESC @6020
//enchanter cantrip: drowse
COPY ~TomeAndBlood/data/cantrips/d5_maen.spl~ ~override~
	SAY NAME1 @6021
	SAY UNIDENTIFIED_DESC @6022
COPY ~TomeAndBlood/data/cantrips/d5_wien.spl~ ~override~
	SAY NAME1 @6021
	SAY UNIDENTIFIED_DESC @6022
//illusionist cantrip: bedazzle
COPY ~TomeAndBlood/data/cantrips/d5_mail.spl~ ~override~
	SAY NAME1 @6023
	SAY UNIDENTIFIED_DESC @6024
COPY ~TomeAndBlood/data/cantrips/d5_wiil.spl~ ~override~
	SAY NAME1 @6023
	SAY UNIDENTIFIED_DESC @6024
//invoker cantrip: magic bolt
COPY ~TomeAndBlood/data/cantrips/d5_main.spl~ ~override~
	SAY NAME1 @6025
	SAY UNIDENTIFIED_DESC @6026
	WRITE_SHORT 0x098 ~%d5_msred%~
COPY ~TomeAndBlood/data/cantrips/d5_wiin.spl~ ~override~
	SAY NAME1 @6025
	SAY UNIDENTIFIED_DESC @6026
	WRITE_SHORT 0x098 ~%d5_msred%~
//necromancer cantrip: stiffen bones
COPY ~TomeAndBlood/data/cantrips/d5_mane.spl~ ~override~
	SAY NAME1 @6027
	SAY UNIDENTIFIED_DESC @6028
COPY ~TomeAndBlood/data/cantrips/d5_wine.spl~ ~override~
	SAY NAME1 @6027
	SAY UNIDENTIFIED_DESC @6028
//transmuter cantrip: earthen grasp
COPY ~TomeAndBlood/data/cantrips/d5_matr.spl~ ~override~
	SAY NAME1 @6029
	SAY UNIDENTIFIED_DESC @6030
COPY ~TomeAndBlood/data/cantrips/d5_witr.spl~ ~override~
	SAY NAME1 @6029
	SAY UNIDENTIFIED_DESC @6030
//fire bolt
COPY ~TomeAndBlood/data/cantrips/d5_mfir.spl~ ~override~
	SAY NAME1 @6031
	SAY UNIDENTIFIED_DESC @6032
COPY ~TomeAndBlood/data/cantrips/d5_wfir.spl~ ~override~
	SAY NAME1 @6031
	SAY UNIDENTIFIED_DESC @6032
	WRITE_SHORT 0x098 ~%d5_msorn%~
//ice bolt
COPY ~TomeAndBlood/data/cantrips/d5_mcld.spl~ ~override~
	SAY NAME1 @6033
	SAY UNIDENTIFIED_DESC @6034
COPY ~TomeAndBlood/data/cantrips/d5_wcld.spl~ ~override~
	SAY NAME1 @6033
	SAY UNIDENTIFIED_DESC @6034
	WRITE_SHORT 0x098 ~%d5_mswhi%~
//acid bolt
COPY ~TomeAndBlood/data/cantrips/d5_macd.spl~ ~override~
	SAY NAME1 @6035
	SAY UNIDENTIFIED_DESC @6036
COPY ~TomeAndBlood/data/cantrips/d5_wacd.spl~ ~override~
	SAY NAME1 @6035
	SAY UNIDENTIFIED_DESC @6036
	WRITE_SHORT 0x098 ~%d5_msgrn%~
//electric bolt
COPY ~TomeAndBlood/data/cantrips/d5_melc.spl~ ~override~
	SAY NAME1 @6037
	SAY UNIDENTIFIED_DESC @6038
COPY ~TomeAndBlood/data/cantrips/d5_welc.spl~ ~override~
	SAY NAME1 @6037
	SAY UNIDENTIFIED_DESC @6038
	WRITE_SHORT 0x098 ~%d5_msblu%~
//earth bolt
COPY ~TomeAndBlood/data/cantrips/d5_wert.spl~ ~override~
	SAY NAME1 @6039
	SAY UNIDENTIFIED_DESC @6040
	WRITE_SHORT 0x098 ~%d5_msbrn%~
//shield spell now protects against cantrips
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_maab~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wiab~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_maen~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wien~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_main~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wiin~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_mail~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wiil~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_mane~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wine~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_madi~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_widi~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_matr~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_witr~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_maco~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wico~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wfir~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_welc~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wcld~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wacd~ END
	BUT_ONLY
COPY_EXISTING ~spwi114.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode=206 target=1 resist_dispel=3 timing=0 duration=300 power=1 STR_VAR resource=~d5_wert~ END
	BUT_ONLY 
	
//adding cantrips to appropriate mages
APPEND ~CLABMA01.2da~ ~CANTRIPS GA_D5_CANT1 ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 

APPEND ~CLABMA02.2da~ ~CANTRIPS GA_D5_WIAB ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

APPEND ~CLABMA03.2da~ ~CANTRIPS GA_D5_WINE ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

APPEND ~CLABMA04.2da~ ~CANTRIPS GA_D5_WITR ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 

APPEND ~CLABMA05.2da~ ~CANTRIPS GA_D5_WIDI ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 

APPEND ~CLABMA06.2da~ ~CANTRIPS GA_D5_WICO ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 

APPEND ~CLABMA07.2da~ ~CANTRIPS GA_D5_WIIN ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

APPEND ~CLABMA08.2da~ ~CANTRIPS GA_D5_WIIL ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 

APPEND ~CLABMA09.2da~ ~CANTRIPS GA_D5_WIEN ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ 
		
APPEND ~CLABSO01.2da~ ~CANTRIPS GA_D5_WFIR ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~		

//updating descriptions
//9563
	ACTION_GET_STRREF 9563 mage
	OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
	  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
	END
	STRING_SET_EVALUATE 9563 ~%mage%~
	//17245
	ACTION_GET_STRREF 17245 mage
	OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
	  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
	END
	STRING_SET_EVALUATE 17245 ~%mage%~
	//9564: abjurer
		ACTION_GET_STRREF 9564 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Protective Shell cantrip.~
		END
		STRING_SET_EVALUATE 9564 ~%mage%~
		//9565: conjurer
		ACTION_GET_STRREF 9565 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Conjure Rabbit cantrip.~
		END
		STRING_SET_EVALUATE 9565 ~%mage%~
		//9566: diviner
		ACTION_GET_STRREF 9566 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Anticipation cantrip.~
		END
		STRING_SET_EVALUATE 9566 ~%mage%~
		//9567: enchanter
		ACTION_GET_STRREF 9567 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Drowse cantrip.~
		END
		STRING_SET_EVALUATE 9567 ~%mage%~
		//9568: illusionist
		ACTION_GET_STRREF 9568 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Bedazzle cantrip.~
		END
		STRING_SET_EVALUATE 9568 ~%mage%~
		//9569: invoker
		ACTION_GET_STRREF 9569 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Magic Bolt cantrip.~
		END
		STRING_SET_EVALUATE 9569 ~%mage%~
		//9570: necromancer
		ACTION_GET_STRREF 9570 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Stiffen Bones cantrip.~
		END
		STRING_SET_EVALUATE 9570 ~%mage%~
		//9571: transmuter
		ACTION_GET_STRREF 9571 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Earthen Grasp cantrip.~
		END
		STRING_SET_EVALUATE 9571 ~%mage%~
//bgee	
	ACTION_IF GAME_IS ~bgee~ THEN BEGIN 
		//24233
		ACTION_GET_STRREF 24233 sorcerer
		OUTER_PATCH_SAVE sorcerer ~%sorcerer%~ BEGIN
		  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
		END
		STRING_SET_EVALUATE 24233 ~%sorcerer%~
	END
//bg2ee
	ACTION_IF GAME_IS ~bg2ee~ THEN BEGIN 
		//45866
		ACTION_GET_STRREF 45866 sorcerer
		OUTER_PATCH_SAVE sorcerer ~%sorcerer%~ BEGIN
			REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
		END
		STRING_SET_EVALUATE 45866 ~%sorcerer%~
	END 
//bgee and bg2ee
ACTION_IF GAME_IS ~bgee bg2ee~ THEN BEGIN 
		//24290: abjurer
		ACTION_GET_STRREF 24290 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Protective Shell cantrip.~
		END
		STRING_SET_EVALUATE 24290 ~%mage%~
		//24291: conjurer
		ACTION_GET_STRREF 24291 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Conjure Rabbit cantrip.~
		END
		STRING_SET_EVALUATE 24291 ~%mage%~
		//24292: diviner
		ACTION_GET_STRREF 24292 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Anticipation cantrip.~
		END
		STRING_SET_EVALUATE 24292 ~%mage%~
		//24293: enchanter
		ACTION_GET_STRREF 24293 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Drowse cantrip.~
		END
		STRING_SET_EVALUATE 24293 ~%mage%~
		//24294: illusionist
		ACTION_GET_STRREF 24294 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Bedazzle cantrip.~
		END
		STRING_SET_EVALUATE 24294 ~%mage%~
		//24295: invoker
		ACTION_GET_STRREF 24295 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Magic Bolt cantrip.~
		END
		STRING_SET_EVALUATE 24295 ~%mage%~
		//24296: necromancer
		ACTION_GET_STRREF 24296 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Stiffen Bones cantrip.~
		END
		STRING_SET_EVALUATE 24296 ~%mage%~
		//24297: transmuter
		ACTION_GET_STRREF 24297 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Earthen Grasp cantrip.~
		END
		STRING_SET_EVALUATE 24297 ~%mage%~
END 
//iwdee
	ACTION_IF GAME_IS ~iwdee~ THEN BEGIN 
		//37189
		ACTION_GET_STRREF 37189 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
		  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
		END
		STRING_SET_EVALUATE 37189 ~%mage%~
		//34605
		ACTION_GET_STRREF 34605 sorcerer
		OUTER_PATCH_SAVE sorcerer ~%sorcerer%~ BEGIN
		  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip at 1st level. ~
		END
		STRING_SET_EVALUATE 34605 ~%sorcerer%~
		//37249
		ACTION_GET_STRREF 37249 sorcerer
		OUTER_PATCH_SAVE sorcerer ~%sorcerer%~ BEGIN
		  REPLACE_TEXTUALLY ~May cast arcane spells.~ ~May cast arcane spells.
– May select one cantrip.~
		END
		STRING_SET_EVALUATE 37249 ~%sorcerer%~
//37193: abjurer
		ACTION_GET_STRREF 37193 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Protective Shell cantrip.~
		END
		STRING_SET_EVALUATE 37193 ~%mage%~
		//37196: conjurer
		ACTION_GET_STRREF 37196 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Conjure Rabbit cantrip.~
		END
		STRING_SET_EVALUATE 37196 ~%mage%~
		//37199: diviner
		ACTION_GET_STRREF 37199 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Anticipation cantrip.~
		END
		STRING_SET_EVALUATE 37199 ~%mage%~
		//37202: enchanter
		ACTION_GET_STRREF 37202 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Drowse cantrip.~
		END
		STRING_SET_EVALUATE 37202 ~%mage%~
		//37205: illusionist
		ACTION_GET_STRREF 37205 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Bedazzle cantrip.~
		END
		STRING_SET_EVALUATE 37205 ~%mage%~
		//37208: invoker
		ACTION_GET_STRREF 37208 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Magic Bolt cantrip.~
		END
		STRING_SET_EVALUATE 37208 ~%mage%~
		//37211: necromancer
		ACTION_GET_STRREF 37211 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Stiffen Bones cantrip.~
		END
		STRING_SET_EVALUATE 37211 ~%mage%~
		//37214: transmuter
		ACTION_GET_STRREF 37214 mage
		OUTER_PATCH_SAVE mage ~%mage%~ BEGIN
			REPLACE_TEXTUALLY ~May cast one additional spell per level.~ ~May cast one additional spell per level.
– May use the Earthen Grasp cantrip.~
		END
		STRING_SET_EVALUATE 37214 ~%mage%~
END 

OUTER_SET strref = (0 - 1)

COPY_EXISTING - ~kitlist.2da~ ~override~
	COUNT_2DA_COLS num_cols
		READ_2DA_ENTRIES_NOW ~r2en_kitlist~ num_cols
		FOR (row = 1; row < r2en_kitlist; row += 1) BEGIN
			READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 1 kitname
			PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~DRAGON_DISCIPLE~) BEGIN
			  READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 4 strref
			END
		  END
		ACTION_IF (strref >= 0) BEGIN
		  ACTION_GET_STRREF strref dd
		  OUTER_PATCH_SAVE dd ~%dd%~ BEGIN
			REPLACE_TEXTUALLY CASE_SENSITIVE ~Advantages:~ ~Advantages:
– May use the Fire Bolt cantrip.~
		END
		STRING_SET_EVALUATE strref ~%dd%~
		END 		
				  
*/				  
				  
				  
				  
				  
